/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "All spice production is boosted by unspent rainbow spice": "未用完的彩虹香料促进了所有香料的生产",
    "All spices boost the previous color based on that spice's amount": "所有香料都会根据香料的量来提升之前的颜色",
    "Auto-Prestige Goal (Color Boosts):": "自动声望目标（颜色提升）：",
    "Auto-Prestige Goal (Rainbow Spice):": "自动声望目标（彩虹香料）：",
    "Auto: OFF": "自动关闭",
    "Average rainbow spice gain: undefined": "平均彩虹香料增益：未定义",
    "B: Color shift/boost": "B：颜色偏移/增强",
    "blue spice": "蓝色香料",
    "Blue Spice Agency": "蓝色香料代理",
    "Blue Spice Factory": "蓝色香料厂",
    "Blue Spice Galaxy": "蓝色香料银河",
    "Blue Spice Harvester": "蓝色香料收割机",
    "Blue Spice Machine": "蓝色香料机",
    "Blue Spice Planet": "蓝色香料星球",
    "Blue Spice Strengthener": "蓝色香料增强剂",
    "Boost from buying 10 is squared": "购买 10 的提升是平方的",
    "boosting all normal spice generators 1.00x": "将所有普通香料生成器提升 1.00 倍",
    "boosting all red & yellow spice generators 1.00x": "将所有红色和黄色香料生成器提升 1.00 倍",
    "boosting all red spice generators 1.00x": "将所有红色香料生成器提升 1.00 倍",
    "boosting all red, yellow & green spice generators 1.00x": "将所有红色、黄色和绿色香料生成器提升 1.00 倍",
    "boosting all red, yellow, green & blue spice generators 1.00x": "将所有红色、黄色、绿色和蓝色香料生成器提升 1.00 倍",
    "boosting ALL spice generators 1.00x": "将所有香料生成器提升 1.00 倍",
    "boosting crystallized spice generators 1.00x": "提高结晶香料生成器 1.00 倍",
    "Buy one:": "买一个：",
    "Color boost 10 times to unlock Prestige": "颜色提升 10 倍以解锁声望",
    "Color boosts don't reset progress": "颜色提升不会重置进度",
    "Color Shift": "颜色偏移",
    "Coming soon...": "快来了...",
    "Condensed Generators": "浓缩生成器",
    "Crystal Infusion": "水晶灌注",
    "Crystal infusions also boost crystallized spice production 1.08x": "水晶灌注还可以将结晶香料的产量提高 1.08 倍",
    "CRYSTAL UPGRADES": "水晶升级",
    "crystallized spice": "结晶香料",
    "CRYSTALLIZED SPICE": "结晶香料",
    "Crystallized spice also boosts other colors by its amount": "结晶香料还通过其数量增强其他颜色",
    "Crystallized spice boosts pink spice by its amount": "结晶香料增加粉红色香料的量",
    "Crystallized Spice Furnace": "结晶香料炉",
    "Crystallized spice furnace multipliers are raised to the 1.25 power": "结晶香料炉乘数提高到 1.25 次方",
    "Crystallized spice furnaces produce pink galaxies": "结晶香料炉产生粉红色星系",
    "Crystallized Spice Headquarters": "结晶香料总部",
    "Crystallized Spice Industry": "结晶香料工业",
    "Crystallized Spice Intelligence": "结晶香料智能",
    "Crystallized spice production is boosted based on your color boosts": "结晶香料的产量会根据您的颜色提升而提高",
    "Crystallized spice production is boosted by unspent rainbow spice": "未用完的彩虹香料促进了结晶香料的生产",
    "Crystallized Spice Refinery": "结晶香料精炼厂",
    "Crystallized Spice Singularity": "结晶香料奇点",
    "Crystallized Spice Strengthener": "结晶香料增强剂",
    "DELETE SAVE": "删除保存",
    "DISABLED": "已禁用",
    "EXP Simulator": "经验模拟器",
    "EXPORT": "导出",
    "green spice": "绿色香料",
    "Green Spice Agency": "绿色香料局",
    "Green Spice Factory": "绿色香料厂",
    "Green Spice Galaxy": "绿色香料银河",
    "Green Spice Harvester": "绿色香料收割机",
    "Green Spice Machine": "绿色香料机",
    "Green Spice Planet": "绿色香料星球",
    "Green Spice Strengthener": "绿色香料增强剂",
    "Harvesters produce galaxies of the previous color": "收割机产生以前颜色的星系",
    "Hotkeys:": "快捷键：",
    "I: Buy crystal infusion": "I：购买水晶灌注",
    "IMPORT": "导入",
    "Increase boost from strengtheners/boosts": "增加增强剂/助推器的助推力",
    "Increase boost from strengtheners/shifts": "增加增强剂/班次的推动力",
    "Last 10 prestiges:": "最后10个声望：",
    "LOCKED": "未解锁",
    "M: Max all": "M: 最多",
    "Made by Zakuro": "作者：Zakuro",
    "Max All": "最大全部",
    "Mode: BOOSTS": "模式：提升",
    "Notation": "符号",
    "P: Prestige": "P：声望",
    "pink spice": "粉红香料",
    "Pink Spice Agency": "粉红香料代理",
    "Pink Spice Factory": "粉红香料厂",
    "Pink Spice Galaxy": "粉红香料银河",
    "Pink Spice Harvester": "粉红香料收割机",
    "Pink Spice Machine": "粉红香料机",
    "Pink Spice Planet": "粉红香料星球",
    "Pink Spice Strengthener": "粉红香料增强剂",
    "PRESTIGE UPGRADES": "声望升级",
    "PRESTIGE!": "声望！",
    "Yellow Spice Machine": "黄色香料机",
    "Yellow Spice Planet": "黄色香料星球",
    "Yellow Spice Strengthener": "黄色香料增强剂",
    "1-6: Buy until X of generator": "1-6：购买直到生成器的X",
    "10 color boosts required": "需要 10 次颜色提升",
    "ENABLED": "已启用",
    "Mode: SPICE": "模式：香料",
    "rainbow spice": "彩虹香料",
    "RED": "红色",
    "red spice": "红色香料",
    "Red Spice Agency": "红色香料代理",
    "Red spice boosts every other color by its amount": "红色香料通过其数量增强了其他所有颜色",
    "Red Spice Factory": "红色香料厂",
    "Red Spice Galaxy": "红色香料银河",
    "Red Spice Harvester": "红香料收割机",
    "Red Spice Machine": "红色香料机器",
    "Red Spice Planet": "红色香料星球",
    "Red Spice Strengthener": "红色香料增强剂",
    "Reduce the strengthener price scaling": "减少增强剂价格缩放",
    "Requires 50 red spice galaxies": "需要 50 个红色香料星系",
    "Reset for a new spice color": "重置为新的香料颜色",
    "S: Buy strengthener": "S：购买增强剂",
    "SAVE": "保存",
    "SCIENTIFIC": "科学计数法",
    "SETTINGS": "设置",
    "Shift+1-6: Buy 1 of generator": "Shift+1-6：购买1台生成器",
    "SPICES": "香料",
    "STATISTICS": "统计",
    "Strengtheners also boost the next color": "增强剂也增强了下一种颜色",
    "Times Prestiged stat boosts all spice production": "声望次数 统计数据提高了所有香料的产量",
    "Unlocks automation for color boosts": "解锁自动化以增强色彩",
    "Unlocks automation for crystal infusions": "解锁水晶灌注自动化",
    "Unlocks automation for red spice": "解锁红色香料的自动化",
    "Unlocks crystallized spice": "解锁结晶香料",
    "Unlocks prestige automation": "解锁声望自动化",
    "YELLOW": "黄色",
    "yellow spice": "黄色香料",
    "Yellow Spice Agency": "黄色香料代理",
    "Yellow Spice Factory": "黄色香料工厂",
    "Yellow Spice Galaxy": "黄色香料星系",
    "Yellow Spice Harvester": "黄色香料收割机",
    "Auto: ON": "自动: 已开启",
    "Auto: OFF": "自动: 已关闭",
    "BASE64": "BASE64",
    "CANCER": "癌症",
    "ENGINEERING": "工程",
    "INFINITY": "无限",
    "LETTERS": "字母",
    "LOGARITHM": "对数",
    "MIXED ENGINEERING": "混合工程",
    "MIXED SCIENTIFIC": "混合科学",
    "ROMAN": "罗马",
    "STANDARD": "标准",
    "All spice production is boosted based on unspent rainbow spice": "所有香料的生产都基于未使用的彩虹香料",
    "PRESTIGE": "声望",
    "Unlocks automation for yellow spice": "解锁黄色香料的自动化",
    "BLUE": "蓝色",
    "GREEN": "绿色",
    "PINK": "粉色",
    "Color Boost": "颜色提升",
    "Reset for a spice boost": "重置以提升香料 ",
    "Unlocks automation for pink spice": "解锁粉红色香料的自动化",
    "Boost from buying 10 is raised to the fifth power": "购买 10 的 提升 提高到五次方",
    "A: Ascend": "A: 转生",
    "Ansuz Runes": "Ansuz 符文",
    "ASCEND!": "已转生!",
    "ASCENSION": "转生",
    "Ascension Confirmations": "转生确认",
    "ASCENSION UPGRADES": "转生升级",
    "Auto-Prestige Goal (Seconds):": "自动声望目标（秒）：",
    "Auto-Ascend Goal (Runes):": "自动转生目标（符文）：",
    "Auto-Prestige Delta (Color Boosts):": "自动转生 Delta (颜色提升)",
    "Auto-Prestige Delta (Rainbow Spice):": "自动转生 Delta (彩虹香料)",
    "Convert 1 ᚫ": "转换 1 ᚫ",
    "Convert ALL ᚫ": "转换 全部 ᚫ",
    "Crystal infusions are 10% stronger": "水晶灌注强度提高 10%",
    "Crystal infusions boost crystallized spice production 1.12x": "水晶灌注可将结晶香料产量提高 1.12 倍",
    "Crystallized spice generator multipliers are stronger": "结晶香料生成器倍增器更强",
    "Distribute ALL Runes": "分发所有符文",
    "Jera Runes": "Jera 符文",
    "Othala Runes": "Othala 符文",
    "Last 10 Ascensions:": "最近 10 次转生：",
    "Last 10 Prestiges:": "最近 10 次声望：",
    "Quality of life Prestige upgrades are not reset by Ascension": "转生不会重置生活质量声望升级",
    "Raido Runes": "Raido 符文",
    "Recall ALL Runes": "召回所有符文",
    "Recall Converted Runes": "召回转换的符文",
    "Recall Spent Runes": "召回消耗的符文",
    "RUNES": "符文",
    "Strengtheners are 2x stronger": "强化剂的强度是原来的 2 倍",
    "Strengtheners boost the next color more": "强化剂提升下一个颜色更多",
    "The boost from red spice amount is 50% stronger": "红色香料量的提升增强了 50%",
    "The boost from Times Prestiged stat is stronger": "来自声望次数统计的提升更强",
    "Unlocks Ascension": "解锁转生",
    "Unlocks automation for Ascension": "解锁自动化转生",
    "Unlocks automation for crystallized spice": "解锁结晶香料的自动化",
    "Unlocks automation for Prestige upgrades": "解锁 声望 升级的自动化",
    "Unlocks more options for Prestige automation": "为 声望 自动化解锁更多选项",
    "(based on color boosts)": "（基于颜色提升）",
    "All spice production boosts from upgrades are disabled": "所有来自升级的香料生产提升都被禁用",
    "Ansuz runes can also be spent on other things than conversion": "Ansuz符文也可以用于转换以外的其他事情",
    "Arcane Enchantment": "奥术附魔",
    "arcane spice": "奥术香料",
    "Arcane spice boosts crystallized spice by its amount": "奥术香料通过其数量增加结晶香料",
    "Arcane Spice Cult": "奥术香料崇拜",
    "Arcane Spice Deity": "奥术香料之神",
    "Arcane Spice Glyph": "奥术香料雕文",
    "Arcane spice is boosted based on unused Ansuz runes": "奥术香料基于未使用的安苏兹符文增强",
    "Arcane Spice Shrine": "奥术香料神殿",
    "Arcane Spice Spellbook": "奥术香料法术书",
    "Arcane Spice Strengthener": "奥术香料强化剂",
    "Arcane Spice Wizard": "奥术香料向导",
    "Auto-Ascend Goal (Seconds):": "自动转生目标（秒）：",
    "Challenge Confirmations": "挑战确认",
    "Color boost requirements scale 10x harder": "色彩提升要求提高 10 倍",
    "Crystallized & arcane spice production is disabled": "结晶和奥术香料生产被禁用",
    "Crystallized Spice Empire": "结晶香料帝国",
    "Discord": "Discord",
    "Distribute HALF Runes": "分发半个符文",
    "Each one makes rune power of its own variety, boosting spice production of its respective type(s)": "每一种都产生自己的符文力量，促进其各自类型的香料产量",
    "Enter Challenge": "进入挑战",
    "Entering an Ascension Challenge will reset your current Ascension": "进入转生挑战将重置您当前的转生",
    "Exit Challenge": "退出挑战",
    "Exponent Notation": "指数符号",
    "LONG": "长",
    "Max Half": "最大的一半",
    "Mode: RUNES": "模式：符文",
    "Mode: TIME": "模式：时间",
    "N: Buy arcane enchantment": "N：购买奥术附魔",
    "Pink spice boosts crystallized spice by its amount": "粉红色香料通过其数量增加结晶香料",
    "Red spice boosts crystallized spice by its amount": "红香料增加结晶香料的量",
    "Reward: Crystallized spice multipliers are even stronger": "奖励：结晶香料倍增器更强",
    "Reward: Strengtheners and infusions are even stronger": "奖励：强化剂和输液更加强大",
    "Reward: Unlock arcane spice": "奖励：解锁奥术香料",
    "Shift+M: Max Half": "Shift+M：最大的一半",
    "Times Ascended stat boosts rainbow spice gains": "Times Ascended 统计数据提升了彩虹香料的收益",
    "Times Prestiged stat is no longer reset by Ascension": "声望次数统计 不再被 转生 重置",
    "Unlocks automation for arcane enchantments": "解锁奥术附魔的自动化",
    "You gain 10% of your pending rainbow spice every second": "你每秒获得 10% 的待定彩虹香料",
    "You gain 1x more Times Prestiged stat": "您获得 1 倍以上的 Times Prestiged 统计数据",
    "You must Ascend with the required amount of rainbow spice to complete the Challenge": "您必须带着所需数量的彩虹香料升空才能完成挑战",
    "Your Ansuz runes can be converted into any of the three rune types below": "您的 奥术符文可以转换为以下三种符文类型中的任何一种",
    "ARCANE SPICE": "奥术香料",
    "ASCENSION CHALLENGES": "转生挑战",
    "arcane enchantments do nothing except refresh production": "奥术附魔除了刷新生产什么都不做",
    "Arcane spice boosts itself by its amount": "奥术香料通过其数量提升自身",
    "Arcane spice glyphs produce crystallized spice singularities": "奥术香料字形产生结晶香料奇点",
    "ASCENSION UPGRADES": "转生升级",
    "Boosts from rune power are 2x stronger": "符文力量的提升是 2 倍强",
    "Boosts from rune power are 8x stronger": "符文能量提升 8 倍",
    "CRYSTAL UPGRADES": "水晶升级",
    "CRYSTALLIZED SPICE": "结晶香料",
    "Generators 4-6 don't produce anything": "生成器 4-6 不产生任何东西",
    "Nice try": "不错的尝试",
    "Normal/crystallized spice production stops after 1 second,": "正常/结晶香料生产在 1 秒后停止，",
    "Red spice boosts arcane spice by its amount": "红色香料增加奥术香料的数量",
    "Reward: Boosts from rune power are 4x stronger": "奖励：符文能量提升 4 倍",
    "Reward: Multipliers for generators 4-6 are slightly stronger": "奖励：生成器 4-6 的乘数稍强",
    "Activate Collider": "激活对撞机",
    "Activating the Spice Collider will consume all atomic spice and create unstable spice": "激活香料碰撞器将消耗所有原子香料并产生不稳定的香料",
    "Arcane spice quota:": "奥术香料配额：",
    "Ascension upgrade quota:": "飞升升级名额：",
    "atomic spice": "原子香料",
    "Atomic spice gains are based on total spice produced": "原子香料收益基于总香料产量",
    "Auto-Collapse Goal (Atomic Spice):": "自动坍缩目标（原子香料）：",
    "Auto-Collapse Goal (Seconds):": "自动坍缩目标（秒）：",
    "Automated distribution:": "自动分发：",
    "Average atomic spice gain: undefined": "平均原子香料增益：未定义",
    "Begin Research": "开始研究",
    "C: Collapse": "C：坍缩",
    "Challenge 6 required": "需要挑战 6",
    "COLLAPSE": "坍缩",
    "Collapse 5 times to unlock Research": "坍缩 5 次以解锁研究",
    "Collapse Confirmations": "坍缩确认",
    "COLLAPSE!": "坍缩！",
    "Collider Animations": "对撞机动画",
    "Completed researches:": "已完成的研究：",
    "decayed spice": "腐烂的香料",
    "DEFAULT": "默认",
    "Expected yield:": "预期产量：",
    "HIGH": "高",
    "Last 10 Collapses:": "最后 10 次坍缩：",
    "Quota must not add up to more than 100%": "配额加起来不得超过 100%",
    "Refresh Rate": "刷新率",
    "Research": "研究",
    "RESEARCH": "研究",
    "Reward: Unlocks Collapse": "奖励：解锁坍缩",
    "Rune distribution quota:": "符文分配额度：",
    "Same as Challenge 1, but rune power production is disabled": "与挑战 1 相同，但符文能量生产被禁用",
    "Select a research:": "选择一项研究：",
    "SPICE COLLIDER": "香料对撞机",
    "Stop Ascending After (Atomic Spice):": "在（原子香料）之后停止转生：",
    "Stop Ascending After (Seconds):": "在（秒）之后停止转生：",
    "Text Visibility": "文本可见性",
    "The Distributor": "分销商",
    "The half-life of unstable spice becomes 33% shorter": "不稳定香料的半衰期缩短33%",
    "the resulting energy is boosting all normal spice production 1.00x": "由此产生的能量使所有正常的香料产量提高 1.00 倍",
    "The Spice Collider": "香料对撞机",
    "undefined": "不明确的",
    "unstable spice": "不稳定的香料",
    "Upgrade:": "升级：",
    "When all upgrades have been purchased:": "购买所有升级后：",
    "When not all upgrades have been purchased:": "当并非所有升级都已购买时：",
    "When researching, you gain 1.00 data/sec": "研究时，您获得 1.00 数据/秒",
    "Your unstable spice is decaying away with a half-life of 10 minutes,": "你不稳定的香料正在腐烂，半衰期只有 10 分钟，",
    "PAST COLLAPSES": "历史坍缩",
    "Crystallized spice synergies:": "结晶香料协同作用：",
    "Yellow spice synergies:": "黄色香料协同作用：",
    "Blue spice synergies:": "蓝色香料协同作用：",
    "Green spice synergies:": "绿色香料协同作用：",
    "Red spice synergies:": "红色香料协同作用：",
    "Pink spice synergies:": "粉色香料协同作用：",
    "Portion of atomic spice to use:": "使用的原子香料部分：",
    "Left: Previous subtab": "左箭头：上一个子选项卡",
    "is boosted based on your color boosts": "根据您的颜色提升而提升",
    "yellow antispice": "黄色反香料",
    "YELLOW ANTISPICE": "黄色反香料",
    "is boosted by unspent rainbow spice": "被未使用的彩虹香料提升",
    "X: Exit challenge": "X：退出挑战",
    "You have not yet reached Color augments": "你还没有达到颜色增强",
    "Up: Next tab": "上箭头：下一个选项卡",
    "You must Collapse for the required amount of atomic spice to complete the Challenge": "您必须坍缩所需数量的原子香料才能完成挑战",
    "Your antispice boosts have been reduced due to being in a Collapse challenge": "由于处于坍缩挑战中，您的反香料效果有所降低",
    "Your unstable spice will be completely decayed in a very long time": "你不稳定的香料会在很长一段时间内完全腐烂",
    "Unstable spice decay gives no boost, it instead produces sixth generators": "不稳定的香料衰变没有提升，反而产生第 6 生成器",
    "UNSTABLE SPICE": "不稳定的香料",
    "Stop Ascending After (Real Seconds):": "停止转生后（真实秒数）：",
    "The game runs 99,999x slower, reach the goal in 999 microseconds or less": "游戏运行速度减慢 99,999 倍，在 999 微秒或更短时间内到达目标",
    "red antispice": "红色反香料",
    "RED ANTISPICE": "红色反香料",
    "GREEN ANTISPICE": "绿色反香料",
    "green antispice": "绿色反香料",
    "PURE ANTISPICE": "纯色反香料",
    "pure antispice": "纯色反香料",
    "Entering an Ascension Challenge will reset your current Ascension, and disable Ascension automation in the Challenge": "进入提升挑战将重置您当前的转生，并在挑战中禁用提升自动化",
    "Entering a Collapse Challenge will reset your current Collapse, and disable Collapse automation in the Challenge": "进入坍缩挑战将重置您当前的坍缩，并在挑战中禁用坍缩自动化",
    "Reward: Color augments begin at 4,000,000 color boosts, and unlock a research": "奖励：颜色增强从 4,000,000 颜色增强开始，并解锁一项研究",
    "Reward: Normal spice multipliers are 2.5% stronger, and unlock 2 researches": "奖励：普通香料倍增器强度提高 2.5%，并解锁 2 项研究",
    "Reward: The game runs 2x faster, and unlock a research": "奖励：游戏运行速度提高 2 倍，并解锁一项研究",
    "Reward: Unlock Collapse": "奖励：解锁坍缩",
    "Reward: Unstable spice decay now also produces arcane spice deities, and unlock a research": "奖励：不稳定的香料腐烂现在也会产生奥术香料神灵，并解锁一项研究",
    "Right: Next subtab": "右箭头：下一个子选项卡",
    "Down: Previous tab": "下箭头：上一个标签",
    "Convert HALF ᚫ": "转换一半 ᚫ",
    "Color augment scaling is significantly harsher than color boost scaling": "颜色增强缩放比颜色增强缩放严格得多",
    "Color Augment": "颜色增强",
    "Color augment scaling is much stronger, and color augments begin at 4 color boosts": "颜色增强缩放比例更强，颜色增强从 4 颜色提升开始",
    "Collapse Challenge rewards do not apply in the Challenge they're from": "坍缩挑战奖励不适用于它们来自的挑战",
    "Challenges 1, 3, 4, & 5 simultaneously": "同时挑战 1、3、4 和 5",
    "Auto-Ascend Goal (Real Seconds):": "自动转生目标（真实秒数）：",
    "Auto-Collapse Goal (Real Seconds):": "自动坍缩目标（真实秒数）：",
    "Auto-Prestige Goal (Real Seconds):": "自动声望目标（真实秒数）：",
    "Ascension upgrade prices are also reduced": "转生升级价格也降低了",
    "Gain a spice boost": "获得香料提升",
    "Times Prestiged and Times Ascended statistics are no longer reset by Collapse": "声望次数 和 转生次数 统计不再被 坍缩 重置",
    "Unlocks automation for Collapse": "解锁坍缩自动化",
    "Unlocks automation for runes and arcane spice in the Distributor": "在分销商中解锁符文和奥术香料的自动化",
    "You get 1 free arcane enchantment for every 10 arcane enchantments you have": "每拥有 10 个奥术附魔，您就会获得 1 个免费的奥术附魔",
    "You get 200 free arcane enchantments for every arcane strengthener you have": "每拥有一个奥术强化剂，您就会获得 200 个免费的奥术附魔",
    "Unlocks the Distributor, which can automate Ascension upgrades": "解锁分销商，它可以自动升级 升级",
    "Unspent atomic spice makes the unstable spice decay boost stronger": "未使用的原子香料使不稳定的香料衰变提升更强",
    "Research&nbsp;Completed": "研究已完成",
    "Ansuz rune gains from Ascension are boosted by Times Collapsed stat": "坍缩次数 统计提升了从 转生 获得的 Ansuz 符文",
    "Ascension Challenges are automatically completed when they are unlocked": "转生挑战解锁后自动完成",
    "Atomic spice gains are additionally boosted by total rune power produced": "产生的总符文能量会额外增加原子香料的收益",
    "Quality of life Ascension upgrades are no longer reset by Collapse": "生活质量转生升级不再被坍缩重置",
    "Unstable spice boosts are 50% stronger when unstable spice is completely decayed": "当不稳定的香料完全腐烂时，不稳定的香料增强效果会增强 50%",
    "Unstable spice decay now also boosts arcane spice production": "不稳定的香料腐烂现在也会提升奥术香料的产量",
    "Unstable spice decay now also boosts crystallized spice production": "不稳定的香料腐烂现在也会提升结晶香料的生产",
    "Atomic spice conversion is 10% more efficient": "原子香料转化效率提高 10%",
    "Pause Research": "暂停研究",
    "Rune power is produced 3x faster": "符文能量的产生速度提高了 3 倍",
    "(The unstable spice boost is also disabled)": "（不稳定的香料提升也被禁用）",
    "Arcane spice synergies:": "奥术香料协同作用：",
    "Completing this Challenge is required to Collapse": "完成这个挑战需要坍缩",
    "Activating the Spice Collider will consume some atomic spice and create red antispice": "激活香料碰撞器会消耗一些原子香料并产生红色反香料",
    "ANTISPICE": "反香料",
    "Atomic spice conversion is 5% more efficient": "原子香料转化效率提高 5%",
    "Atomic spice input:": "原子香料输入：",
    "C.UPGRADES": "C.升级",
    "CHALLENGES": "挑战",
    "COLLAPSE CHALLENGES": "坍缩挑战",
    "COLLIDER": "对撞机",
    "CRYSTAL SPICE": "水晶香料",
    "Next research unlock in 1 completion": "下一项研究在 1 次完成后解锁",
    "PRESTIGES": "声望",
    "Red antispice gains are calculated based on total atomic spice used and total red spice": "红色反香料增益是根据使用的总原子香料和总红色香料计算的",
    "Red spice input:": "红香料输入：",
    "Resume Research": "恢复研究",
    "Rune power is produced 2x faster": "符文能量产生速度提高 2 倍",
    "Shift+M: Max half": "Shift+M：最大的一半",
    "Total atomic spice used:": "使用的总原子香料：",
    "Unlocks antispice": "解锁反香料",
    "Unlocks red antispice": "解锁红色反香料",
    "UPGRADES": "升级",
    "You gain 888x more atomic spice for every Collapse challenge completion": "每完成一次 坍缩 挑战，您都会获得 888x 的原子香料",
    "Antispice Perks": "反香料津贴",
    "Ascension is disabled, but Challenge 6 is not required to Collapse": "提升被禁用，但挑战 6 不需要坍缩",
    "basic antispice": "基本反香料",
    "BASIC ANTISPICE": "基本的反香料",
    "blue antispice": "蓝色反香料",
    "BLUE ANTISPICE": "蓝色反香料",
    "boosting crystallized spice production 1.00x,": "将结晶香料产量提高 1.00 倍，",
    "Challenge 7-12 rewards are 5% stronger": "挑战7-12奖励强5%",
    "Color boosts and strengtheners are 30% stronger": "颜色增强剂和增强剂增强 30%",
    "Crystal infusions and arcane enchantments are 5.4% stronger": "水晶注入和奥术结界增强 5.4%",
    "For every five crystallized spice generators bought, that generator's boost is multiplied by 2": "每购买 5 个结晶香料发生器，该发生器的增益就会乘以 2",
    "For every ten blue spice generators purchased, that generator's boost increases by 1": "每购买 10 个蓝色香料发生器，该发生器的增益就会增加 1",
    "For every ten green spice generators purchased, that generator's boost increases by 1": "每购买 10 个绿色香料发生器，该发生器的增益就会增加 1",
    "For every ten pink spice generators purchased, that generator's multiplier increases by 1": "每购买 10 个粉色香料生成器，该生成器的乘数就会增加 1",
    "For every ten red spice generators purchased, that generator's boost increases by 1": "每购买 10 个红色香料发生器，该发生器的增益就会增加 1",
    "For every ten yellow spice generators purchased, that generator's boost increases by 1": "每购买 10 个黄色香料发生器，该发生器的增益就会增加 1",
    "For every three arcane spice generators bought, that generator's boost is multiplied by 3": "每购买三个奥术香料发生器，该发生器的增益就会乘以 3",
    "increasing Prestige and Ascension gains by 0.000%,": "声望和提升增益增加 0.000%，",
    "July 2, 2023": "2023 年 7 月 2 日",
    "pink antispice": "粉红色反香料",
    "PINK ANTISPICE": "粉红反香料",
    "rainbow antispice": "彩虹反香料",
    "RAINBOW ANTISPICE": "彩虹风味",
    "Refund Antispice Perks": "退款反香料津贴",
    "Reward: Color augments begin at 4,000,000 color boosts": "奖励：颜色增强从 4,000,000 颜色增强开始",
    "Reward: Normal spice multipliers are 2.5% stronger": "奖励：普通香料倍数增强 2.5%",
    "Reward: The game runs 2x faster": "奖励：游戏运行速度提高 2 倍",
    "Reward: Unstable spice decay now also produces arcane spice deities": "奖励：不稳定的香料腐烂现在也会产生奥术香料神",
    "Reward: You gain 1% of your pending Ansuz runes every second": "奖励：每秒你获得 1% 的未决安苏兹符文",
    "Reward: You gain data 2x faster while researching": "奖励：研究时获取数据的速度提高 2 倍",
    "Same as Challenge 6, but all research boosts are disabled, and red, yellow, green, & blue spice production is disabled, and the unstable spice boost is not disabled": "与挑战 6 相同，但禁用所有研究增强，禁用红色、黄色、绿色和蓝色香料生产，并且未禁用不稳定的香料增强",
    "The game speed multiplier is 50% stronger outside of Challenge 9": "挑战 9 之外的游戏速度倍增器强 50%",
    "Unlocks Expansion": "解锁扩展",
    "You gain 15% more rainbow spice from Prestige": "你从声望中获得的彩虹香料多 15%",
    "You gain 25% more Ansuz runes from Ascension": "你从提升中获得的安苏兹符文增加 25%",
    "Activating the Spice Collider will consume some atomic spice and create basic antispice": "激活香料碰撞器将消耗一些原子香料并产生基本的反香料",
    "Activating the Spice Collider will consume some atomic spice and create unstable spice": "激活香料碰撞器会消耗一些原子香料并产生不稳定的香料",
    "Activating the Spice Collider will consume some atomic spice and create yellow antispice": "激活香料碰撞器将消耗一些原子香料并产生黄色反香料",
    "ALL spice production multipliers are 1.2% stronger": "所有香料产量乘数增强 1.2%",
    "and making fifth generators 0.000% stronger": "并使第五生成器更强 0.000%",
    "and making sixth generators 0.000% stronger": "并使第六台生成器变得更强 0.000%",
    "Antispice Perks": "反香料津贴",
    "Ascension is disabled, but Challenge 6 is not required to Collapse": "提升被禁用，但挑战 6 不需要坍缩",
    "Atomic spice conversion is 5.00% more efficient": "原子香料转换效率提高 5.00%",
    "basic antispice": "基本反香料",
    "BASIC ANTISPICE": "基本的反香料",
    "Basic antispice gains are calculated based on total atomic spice used": "基本反香料增益是根据使用的原子香料总量计算的",
    "blue antispice": "蓝色反香料",
    "BLUE ANTISPICE": "蓝色反香料",
    "Challenge 7-12 rewards are 5% stronger": "挑战7-12奖励强5%",
    "Color boosts and strengtheners are 30% stronger": "颜色增强剂和增强剂增强 30%",
    "Crystal infusions and arcane enchantments are 5.4% stronger": "水晶注入和奥术结界增强 5.4%",
    "Currently: The game runs 8x faster": "目前：游戏运行速度提高了 8 倍",
    "For every five crystallized spice generators bought, that generator's boost is multiplied by 2": "每购买 5 个结晶香料发生器，该发生器的增益就会乘以 2",
    "For every ten blue spice generators purchased, that generator's boost increases by 1": "每购买 10 个蓝色香料发生器，该发生器的增益就会增加 1",
    "For every ten green spice generators purchased, that generator's boost increases by 1": "每购买 10 个绿色香料发生器，该发生器的增益就会增加 1",
    "For every ten pink spice generators purchased, that generator's multiplier increases by 1": "每购买 10 个粉色香料生成器，该生成器的乘数就会增加 1",
    "For every ten red spice generators purchased, that generator's boost increases by 1": "每购买 10 个红色香料发生器，该发生器的增益就会增加 1",
    "For every ten yellow spice generators purchased, that generator's boost increases by 1": "每购买 10 个黄色香料发生器，该发生器的增益就会增加 1",
    "For every three arcane spice generators bought, that generator's boost is multiplied by 3": "每购买三个奥术香料发生器，该发生器的增益就会乘以 3",
    "increasing Prestige and Ascension gains by 0.000%,": "声望和提升增益增加 0.000%，",
    "making color boosts and ALL strengtheners 548x stronger,": "使颜色增强和所有增强剂增强 548 倍，",
    "Next: The game runs 16x faster": "下一篇：游戏运行速度提高 16 倍",
    "pink antispice": "粉红色反香料",
    "PINK ANTISPICE": "粉红反香料",
    "rainbow antispice": "彩虹反香料",
    "RAINBOW ANTISPICE": "彩虹风味",
    "Refund Antispice Perks": "退款反香料津贴",
    "Reward: Color augments begin at 4,000,000 color boosts": "奖励：颜色增强从 4,000,000 颜色增强开始",
    "Reward: The game runs 2x faster": "奖励：游戏运行速度提高 2 倍",
    "Reward: Unstable spice decay now also produces arcane spice deities": "奖励：不稳定的香料腐烂现在也会产生奥术香料神",
    "Reward: You gain 1% of your pending Ansuz runes every second": "奖励：每秒你获得 1% 的未决安苏兹符文",
    "Reward: You gain data 2x faster while researching": "奖励：研究时获取数据的速度提高 2 倍",
    "Same as Challenge 6, but all research boosts are disabled, and red, yellow, green, & blue spice production is disabled, and the unstable spice boost is not disabled": "与挑战 6 相同，但禁用所有研究增强，禁用红色、黄色、绿色和蓝色香料生产，并且未禁用不稳定的香料增强",
    "The game speed multiplier is 50% stronger outside of Challenge 9": "挑战 9 之外的游戏速度倍增器强 50%",
    "The half-life of unstable spice becomes 33.0% shorter": "不稳定香料的半衰期缩短33.0%",
    "Unlocks Expansion": "解锁扩展",
    "Unlocks yellow antispice": "解锁黄色反香料",
    "Yellow antispice gains are calculated based on total atomic spice used and total yellow spice": "黄色反香料增益是根据使用的原子香料总量和黄色香料总量计算的",
    "Yellow spice input:": "黄色香料输入：",
    "You gain 15% more rainbow spice from Prestige": "你从声望中获得的彩虹香料多 15%",
    "You gain 25% more Ansuz runes from Ascension": "你从提升中获得的安苏兹符文增加 25%",
    "You get 50 free arcane enchantments for every Collapse (up to 50% of your bought arcane enchantments)": "每次崩溃你都会获得 50 个免费的奥术结界（最多可达你购买的奥术结界的 50%）",
    "Your unstable spice will be completely decayed in -Infinity seconds real time": "您不稳定的香料将在无限秒内实时完全腐烂",
    "SHOW": "显示",
    "Reduce Flashing": "减少闪烁",
    "Reset Layer Resource/min": "重置层资源/分钟",
    "HIDE": "隐藏",
    "\"Unstable spice\" is the first new spice that was created in the Spice Collider. It is highly radioactive and does not want to stay in this form, thus it decays over time into its lower energy form, known as \"decayed spice\".": "“不稳定的香料”是在香料碰撞器中创建的第一个新香料。 它具有高放射性，并且不想保持这种形式，因此它会随着时间的推移衰变为较低能量的形式，称为“腐烂的香料”。",
    "4th, 5th, and 6th generators don't produce anything": "第四、第五和第六个生成器不产生任何东西",
    "Unstable spice was initially thought of as a failure of the Spice Collider. However, your scientists soon noticed that the transformation from unstable spice into decayed spice releases an incredible amount of energy. This has many applications for potential weaponry, or in the energy industry. It may even be yet another source of power for your spice empire's growth.": "不稳定的香料最初被认为是香料碰撞器的失败。 然而，你们的科学家很快注意到，从不稳定的香料到腐烂的香料的转变会释放出令人难以置信的能量。 这在潜在武器或能源工业中有许多应用。 它甚至可能成为您的香料帝国发展的另一个动力源泉。",
    "The first type of spice produced unnaturally, rainbow spice exists as the fusion of the five natural spice colors into one spice. This amalgamation causes rainbow spice to be very highly reactive, even in small quantities.": "彩虹香料是第一种非自然产生的香料，它是由五种天然香料颜色融合成一种香料而存在的。 这种混合导致彩虹香料即使数量很少，也具有非常高的反应性。",
    "Rehashing the same idea as Crystal Infusions, a similar device can be created that utilizes arcane spice's abilities to enhance the efficiency of your crystallized spice production by an enormous amount. This higher, more specialized variant of the Crystal Infusion has been dubbed an \"Arcane Enchantment\".": "重申与水晶注入相同的想法，可以创建一个类似的设备，利用奥术香料的能力来大幅提高结晶香料的生产效率。 这种更高级、更专业的水晶注入变体被称为“奥术结界”。",
    "Following the discovery of atomic spice, your scientists invented an enormous contraption: the Spice Collider. It accelerates individual units of atomic spice to incredible speeds before letting them collide, for the purpose of researching whatever may result from this event. The Spice Collider will allow you to gain further insights into atomic spice and the nature of all spices, and potentially even create new spices.": "在发现原子香料之后，你们的科学家发明了一种巨大的装置：香料对撞机。 它将单个原子香料单元加速到令人难以置信的速度，然后让它们发生碰撞，以研究该事件可能产生的结果。 香料碰撞器将使您能够进一步了解原子香料和所有香料的性质，甚至有可能创造出新的香料。",
    "Each Color Boost gathers more and more energy, and with enough of it, spice fusion is possible. All five of your spice colors can be fused together, although without even more energy an efficient fusion isn't possible. As such, most of your spices will be lost in the process, but what survives will be in the form of a new spice: rainbow spice.": "每个颜色增强都会收集越来越多的能量，只要有足够的能量，香料融合就有可能。 所有五种香料颜色都可以融合在一起，尽管没有更多的能量，有效的融合是不可能的。 因此，大部分香料都会在此过程中丢失，但幸存下来的将以新香料的形式出现：彩虹香料。",
    "The data from your last Color Shift led you to the discovery of pink spice, but it also seems to suggest that there are no more natural spices to discover. Following this realization, your empire has decided to instead focus the gathered energy on empowering the production of the five spice colors you already have in your inventory. This new, different usage of the Color Shift device is instead called a \"Color Boost\".": "上次颜色转变的数据引导您发现了粉红色香料，但它似乎也表明没有更多的天然香料可供发现。 认识到这一点后，您的帝国决定将聚集的精力集中在库存中已有的五种香料颜色的生产上。 这种新的、不同的颜色偏移设备用法被称为“颜色增强”。",
    "The device behind Color Shifts and Color Boosts can be modified to create a new device. This device can instead be fed with crystallized spice, and produces a much more substantial boost to the production of the ordinary spice colors. This third iteration of the Color Shift idea is called a \"Crystal Infusion\".": "可以修改颜色偏移和颜色增强背后的设备来创建新设备。 该设备可以添加结晶香料，并对普通香料颜色的生产产生更显着的促进作用。 色移理念的第三次迭代称为“水晶注入”。",
    "The raw runes conjured into being by Ascension are all of the same composition, and they all bear the same glyph: the Ansuz rune. These Ansuz runes have no inherent abilities. Their purpose lies instead in serving as a vessel for transmutation into other rune types. These other runes continuously radiate energies of different kinds, which will greatly empower your empire moving forward.": "转生所创造的原始符文都具有相同的成分，并且都带有相同的雕文：安苏兹符文。 这些安苏兹符文没有固有的能力。 相反，它们的目的在于充当转变为其他符文类型的容器。 这些其他符文不断散发出不同种类的能量，这将极大地增强你的帝国前进的力量。",
    "The second discovery brought by the Spice Collider: smashing units of atomic spice together sometimes creates the \"opposite\" of atomic spice, which is now considered as the basic form of \"antispice\". Additionally, your researchers theorize that colliding ordinary spice types with basic antispice may create the \"opposite\" of those spice types.": "香料对撞机带来的第二个发现：将原子香料单位粉碎在一起有时会产生原子香料的“对立面”，现在被认为是“反香料”的基本形式。 此外，您的研究人员推测，普通香料类型与基本反香料的碰撞可能会产生这些香料类型的“相反”。",
    "Your empire has found a device that - when fed a large amount of spices - returns a lot of energy and data, leading your researchers to discover a new 'color' of spice. This event has been dubbed a \"Color Shift\", and your researchers predict that subsequent Color Shifts may reveal even more colors.": "你的帝国发现了一种装置，当喂入大量香料时，它会返回大量能量和数据，引导你的研究人员发现香料的新“颜色”。 这一事件被称为“颜色转变”，研究人员预测后续的颜色转变可能会显示出更多的颜色。",
    "Offline Progress": "离线进度",
    "NO": "否",
    "OK": "确定",
    "After your empire seemingly somehow exhausted all resources in the universe, the discovery of Realms followed almost immediately. What you once thought was the whole universe was really just a single Realm in the incomprehensibly even more vast universe. The new theory is that each Realm is a separate, self-contained \"bubble\" in the universe, and that most civilizations inside them consider their Realm to be all there is.": "在你的帝国似乎以某种方式耗尽了宇宙中的所有资源之后，国度的发现几乎立即发生。 你曾经以为的整个宇宙实际上只是更广阔的宇宙中的一个领域。 新理论认为，每个领域都是宇宙中一个独立的、独立的“气泡”，其中的大多数文明都认为它们的领域就是一切。",
    "After a breakthrough, your empire discovered not only yellow spice, but also that more spice colors are probable to exist. While these spice colors are unsurprisingly far less ubiquitous than red spice, it seems large spice empires have already been utilizing them before you.": "取得突破后，你的帝国不仅发现了黄色香料，而且还可能存在更多颜色的香料。 毫不奇怪，这些香料颜色远不如红色香料那么普遍，但大型香料帝国似乎已经在您之前使用它们了。",
    "Alert modal text here": "此处提示模态文本",
    "All spice production boosts from Prestige and Ascension upgrades": "所有香料产量均来自声望和提升升级",
    "and Collapse Challenge rewards do not apply in the Challenge they're from": "和折叠挑战奖励不适用于他们所在的挑战",
    "and strengthener price scaling 3x -> 2x": "强化剂价格缩放 3 倍 -> 2 倍",
    "ARCANE ENCHANTMENTS": "奥术结界",
    "Arcane spice glyphs produce crystallized spice galaxies": "奥术香料雕文产生结晶香料星系",
    "Arcane spice has an unexpectedly strong bitter flavor, but this does not stop it from finding its niche in your culinary industry.": "奥术香料具有出乎意料的强烈苦味，但这并不能阻止它在烹饪行业中找到自己的位置。",
    "Arcane spice's influence over the spacetime continuum seems to transcend the very laws of physics themselves - almost like magic - and this ability is still not well understood.": "奥术香料对时空连续体的影响似乎超越了物理定律本身——几乎就像魔法一样——而这种能力仍然没有得到很好的理解。",
    "are disabled, and rune power production is disabled": "被禁用，并且符文能量生产被禁用",
    "Ascension automation and rainbow spice multipliers are disabled in Ascension Challenges": "转生自动化和彩虹香料倍增器在转生挑战中被禁用",
    "ATOMIC SPICE": "原子香料",
    "Auto-Ascend Delta (Runes):": "自动上升三角洲（符文）：",
    "Auto-Collapse Goal (Real Seconds after Full Decay):": "自动崩溃目标（完全衰减后的真实秒数）：",
    "Begin Your Empire": "开始你的帝国",
    "BLUE SPICE": "蓝色香料",
    "Blue Spice Corporation": "蓝色香料公司",
    "Blue spice's structure causes it to favor endothermic reactions. Because of this, it has an exceptional ability to cool things. This has a variety of applications such as refrigeration, or as a coolant for mechanical or electrical systems.": "蓝色香料的结构使其有利于吸热反应。 正因为如此，它具有非凡的冷却能力。 它有多种应用，例如制冷，或作为机械或电气系统的冷却剂。",
    "Boosts from rune power are 50% stronger": "符文能量的提升强 50%",
    "Boosts from rune power are now 3x stronger": "符文能量的提升现在强 3 倍",
    "CANCEL": "取消",
    "Catching up on time since the game was last saved...": "自从上次保存游戏以来正赶上时间......",
    "Collapse automation and atomic spice multipliers are disabled in Collapse Challenges,": "崩溃自动化和原子香料倍增器在崩溃挑战中被禁用，",
    "COLOR AUGMENTS": "色彩增强",
    "COLOR BOOSTS": "色彩增强",
    "Color boosts and strengtheners are 17.5% stronger": "颜色增强剂和增强剂增强 17.5%",
    "COLOR SHIFTS": "颜色变化",
    "COMPENDIUM": "概要",
    "Confirmation modal text here": "此处确认模式文本",
    "Confused? After the v1.7.0 update of Spice Idle, the game is no longer compatible with older versions.": "使困惑？ Spice Idle v1.7.0更新后，游戏不再兼容旧版本。",
    "CRYSTAL INFUSIONS": "水晶浸剂",
    "Crystal infusions and arcane enchantments are 6% stronger": "水晶注入和奥术结界增强 6%",
    "Crystal infusions are 25% stronger": "水晶注入强度增强 25%",
    "Crystal infusions cannot be purchased": "水晶输液无法购买",
    "Crystallized Spice Corporation": "结晶香料公司",
    "Crystallized Spice Division": "结晶香料事业部",
    "Crystallized Spice Galaxy": "结晶香料银河",
    "Crystallized spice is created by placing pink spice into a blast furnace, and heating it up until it melts. After removing it from the furnace, it will cool and crystallize into a solid form. The explosive properties of rainbow spice are integral to the operation of this furnace.": "结晶香料是通过将粉红色香料放入高炉中加热直至融化而制成的。 将其从炉中取出后，它会冷却并结晶成固体形式。 彩虹香料的爆炸特性对于该熔炉的操作至关重要。",
    "Crystallized Spice Planet": "结晶香料星球",
    "Current Auto-Ascend Goal: +1 ᚫ": "当前自动提升目标：+1ᚫ",
    "Current Auto-Prestige Goal: 10 color boosts": "当前自动声望目标：10 种颜色提升",
    "Currently running about 0 ticks/sec": "当前运行速度约为 0 ticks/秒",
    "Entering a Collapse Challenge will reset your current Collapse": "进入崩溃挑战将重置您当前的崩溃",
    "GREEN SPICE": "绿色香料",
    "Green Spice Corporation": "绿色香料公司",
    "Green spice has an incredibly nutrient-rich composition, allowing it to perform very well as a fertilizer. For this reason, it is now the dominant resource for your empire's agricultural practices.": "绿色香料具有极其丰富的营养成分，使其能够很好地用作肥料。 因此，它现在是你们帝国农业实践的主要资源。",
    "However, the explosive abilities of rainbow spice are not to be underestimated, and they have many applications if used in a controlled manner. The study of rainbow spice is sure to unveil many powerful tools for your empire.": "然而，彩虹香料的爆炸能力不容小觑，如果控制得当，它们还有很多用途。 对彩虹香料的研究一定会为你的帝国揭开许多强大的工具。",
    "However, this nutrient-rich composition gives it a considerable earthy flavor, so it is rarely seen used as an actual spice.": "然而，这种营养丰富的成分赋予它相当大的泥土风味，因此很少被用作真正的香料。",
    "If you'd like to continue in the new game from about where you were, you should check out the": "如果您想从原来的位置继续玩新游戏，您应该查看",
    "January 30, 2024": "2024 年 1 月 30 日",
    "Minimum time between activations:": "激活之间的最短时间：",
    "Paste your exported save code here:": "将导出的保存代码粘贴到此处：",
    "PINK SPICE": "粉红香料",
    "Pink Spice Corporation": "粉红香料公司",
    "Pink spice has a surprising amount of structural integrity. It loves to stick together, and as such it makes for a very good adhesive. It is also useful as an ingredient in building materials to make them more durable.": "粉红香料具有惊人的结构完整性。 它喜欢粘在一起，因此它是一种非常好的粘合剂。 它也可用作建筑材料的成分，使其更耐用。",
    "Please keep the game on-screen": "请保持游戏在屏幕上",
    "Portion of rune gains to distribute:": "分配的符文增益部分：",
    "RAINBOW SPICE": "彩虹香料",
    "Rather than negating the properties of their ordinary counterparts, the antispice variants of a spice may instead amplify their abilities, and may even cause entirely new abilities to manifest. The efficiency of harvest of that spice type might also be greatly increased.": "香料的反香料变体并不会否定其普通对应物的特性，反而可能会增强它们的能力，甚至可能会导致全新的能力显现出来。 该香料类型的收获效率也可能大大提高。",
    "REALMS": "领域",
    "RED SPICE": "红香料",
    "Red Spice Corporation": "红香料公司",
    "Red spice has the ordinary spicy flavor that you would expect from a spice, and as such it is an obvious choice for many dishes.": "红色香料具有您所期望的香料的普通辛辣味道，因此它是许多菜肴的明显选择。",
    "Reset": "重置",
    "Reward: 4th generators are 3% stronger, 5th generators are 6%": "奖励：第4个生成器强3%，第5个生成器强6%",
    "Reward: Boosts from rune power are now 2x stronger": "奖励：符文能量的提升现在强 2 倍",
    "Reward: Color augments begin at 4,194,304 color boosts": "奖励：颜色增强从 4,194,304 种颜色增强开始",
    "Reward: Strengtheners are 3x stronger, infusions are 20% stronger,": "奖励：强化剂强3倍，输液强20%，",
    "s real time": "实时",
    "Same as Challenge 6, but all research boosts are disabled, and red, yellow, green, & blue spice production is disabled": "与挑战 6 相同，但所有研究提升均被禁用，并且红色、黄色、绿色和蓝色香料生产被禁用",
    "Savebank": "储蓄银行",
    "Similarly, it has a cool and refreshing flavor, finding its way as an ingredient in many cold beverages.": "同样，它具有清凉清爽的味道，可以作为许多冷饮的成分。",
    "Skip Half of Ticks": "跳过一半的ticks",
    "Skip Offline Progress": "跳过离线进度",
    "Spice deposits can be found on just about any planet, on the surface or underground. They can be gathered with a Harvester, a very basic tool that even primitive civilizations can make.": "香料沉积物几乎可以在任何星球上找到，无论是地表还是地下。 它们可以用收割机来收集，收割机是一种非常基本的工具，即使是原始文明也可以制造。",
    "Spice Idle": "香料放置",
    "Spice Idle Classic": "香料空闲经典",
    "Spices are a fundamental substance that govern almost everything that goes on in your universe. They are the first commodity of any civilization, and become the most integral part of their economies.": "香料是一种基本物质，几乎控制着宇宙中发生的一切。 它们是任何文明的首要商品，并成为其经济中最重要的组成部分。",
    "Spices can be found everywhere in this universe, and you've set it upon yourself to exploit them to conquer the universe with your spice empire.": "香料在这个宇宙中随处可见，你已经下定决心要利用它们，用你的香料帝国征服宇宙。",
    "stronger, and 6th generators are 10% stronger": "更强，第 6 台生成器更强 10%",
    "The boost from red spice amount is 2x stronger": "红色香料量的提升强度是原来的 2 倍",
    "The discovery of atomic spice may just be the key to the continued growth of your spice empire. Atomic spice is the smallest, indivisible and most fundamental unit of spice. All spice types are ultimately made of atomic spice, arranged into different structures and formations.": "原子香料的发现可能是你的香料帝国持续发展的关键。 原子香料是香料中最小的、不可分割的、最基本的单位。 所有香料类型最终都是由原子香料制成，排列成不同的结构和形式。",
    "The flavor of pink spice is sweet and intensely fruity, making it a highly sought after ingredient for many confections and candies.": "粉红香料的味道甜美且果香浓郁，使其成为许多糖果和糖果中备受追捧的成分。",
    "The flavor of rainbow spice is unknown, as consuming enough rainbow spice to get any sense of flavor from it would be almost instantly lethal.": "彩虹香料的味道尚不清楚，因为食用足够的彩虹香料来从中获得任何味道几乎会立即致命。",
    "The free crystal infusions upgrade is uncapped": "免费水晶灌注升级无上限",
    "The game runs 100,000x slower, reach the goal in 500 microseconds or less": "游戏运行速度慢 100,000 倍，在 500 微秒或更短的时间内达到目标",
    "The game speed multiplier is 25% stronger outside of Challenge 9": "除挑战 9 之外，游戏速度倍增增强 25%",
    "The material the cosmic runes are made of has finally been identified. It is an entirely new type of spice your researchers are calling \"arcane spice\". You've also found a way to use the powers of the runes to channel it into being in spice form.": "宇宙符文的材质终于被确定了。 这是一种全新类型的香料，你们的研究人员称之为“神秘香料”。 您还找到了一种使用符文力量将其转化为香料形式的方法。",
    "The material these runes are constructed out of remains a mystery, but studying them may unlock some very strong abilities for your spice empire.": "这些符文的构成材料仍然是个谜，但研究它们可能会为你的香料帝国解锁一些非常强大的能力。",
    "THE SPICE COLLIDER": "香料对撞机",
    "The spice native to your homeworld has a very red hue, giving it its name. Red spice is quite common in the universe, and most spice empires will start their journey with it.": "这种原产于你家乡的香料具有非常红色的色调，因此得名。 红色香料在宇宙中相当常见，大多数香料帝国都会从它开始他们的旅程。",
    "THE SPICE UNIVERSE": "香料宇宙",
    "The study and mastery of atomic spice manipulation may pave the way to some interesting new means of progression.": "对原子香料操纵的研究和掌握可能会为一些有趣的新进展方法铺平道路。",
    "The universe is full of spices...": "宇宙充满了香料......",
    "These two properties together make pink spice the most valuable spice you've discovered by far, and it easily becomes the defining commodity in the economies of all spice empires that get their hands on it.": "这两种特性共同使粉红色香料成为您迄今为止发现的最有价值的香料，并且它很容易成为所有掌握它的香料帝国经济中的决定性商品。",
    "This new solid form of pink spice enhances its cohesiveness even further, making crystallized spice a nearly indestructible material. This will be incredibly useful for just about anything your empire could build.": "这种新的固体形式的粉红色香料进一步增强了其凝聚力，使结晶香料成为几乎坚不可摧的材料。 这对于你的帝国可以建立的任何东西都非常有用。",
    "This spice fusion event is known as \"Prestige\".": "这项香料融合活动被称为“Prestige”。",
    "Ticks to run at once:": "立即运行的 ticks：",
    "Time: GAME TIME": "时间：比赛时间",
    "Unit: RAINBOW SPICE": "单位：彩虹香料",
    "Use them to conquer it": "用它们来征服它",
    "When subject to enough pressure, red spice can emit a significant amount of heat, making it useful for a variety of industrial and culinary applications.": "当受到足够的压力时，红色香料会散发出大量的热量，使其可用于各种工业和烹饪应用。",
    "YELLOW SPICE": "黄香料",
    "Yellow Spice Corporation": "黄色香料公司",
    "Yellow spice has a distinctive sour, almost citrusy flavor, and is now often used in sour candies and other similar foods in that niche.": "黄色香料具有独特的酸味，几乎是柑橘味，现在经常用于酸味糖果和该领域的其他类似食品。",
    "Yellow spice has an exceptional capacity for absorbing and retaining energy, making it useful as both an energy source and an efficient method of energy storage. Due to these properties, natural yellow spice is often found already full of energy.": "黄色香料具有吸收和保留能量的特殊能力，使其既可用作能源，又可作为有效的能量储存方法。 由于这些特性，天然黄色香料通常已经充满活力。",
    "YES": "是的",
    "You can find v1.6.5 (and your old save) on": "您可以在以下位置找到 v1.6.5（以及您的旧保存）",
    "You gain 10% more rainbow spice from Prestige": "你从声望中获得的彩虹香料多 10%",
    "You gain 12.5% more Ansuz runes from Ascension": "你从提升中获得的安苏兹符文增加 12.5%",
    "Your empire has finally surpassed all other spice empires, and you should be proud of this accomplishment. But, you now find trouble gathering enough spices for Color Boosts, when you didn't before. Perhaps you're missing something...": "你的帝国终于超越了所有其他香料帝国，你应该为这一成就感到自豪。 但是，你现在发现很难收集足够的香料来增强颜色，而以前却没有。 也许你错过了一些东西......",
    "Your empire is now starting to rival even the largest spice empires, and your studies have led to the discovery of the ways of Ascension. You can now Ascend your empire to the next plane of being. All will be left behind, but in the process, mysterious cosmic runes manifest into existence.": "你们的帝国现在开始与最大的香料帝国相媲美，你们的研究已经导致了转生之路的发现。 您现在可以将您的帝国提升到下一个存在层面。 一切都将被抛在身后，但在这个过程中，神秘的宇宙符文会显现出来。",
    "Your researchers have been on the issue for awhile, and they've found that you have just enough resources to Collapse the universe. By dismantling the entire universe, a new entity known as \"atomic spice\" can be extracted. The universe is then reassembled.": "你们的研究人员已经研究这个问题有一段时间了，他们发现你们有足够的资源来让宇宙崩溃。 通过拆解整个宇宙，可以提取出一种被称为“原子香料”的新实体。 然后宇宙重新组合。",
    "DECAY": "衰变",
    "GAME TIME": "游戏时间",
    "REAL TIME": "现实时间",
    "SPICE": "香料",
    "TIME": "时间",
    "BOOSTS": "提升",
    "(Dark spice and galactic shards are unaffected by these effects)": "（黑暗香料和星系碎片不受这些影响）",
    "↓ More ↓": "↓ 更多 ↓",
    "Switch view automatically:": "Switch view automatically:",
    "Dark Construct": "黑暗构造",
    "Dark Conversion": "黑暗转换",
    "Current Realm": "当前领域",
    "Buy Max": "购买最大",
    "dark spice": "黑暗香料",
    "DARK SPICE": "黑暗香料",
    "Dark Spice Accelerator": "黑暗香料加速器",
    "Dark Spice Civilization": "黑暗香料文明",
    "Dark Spice Colony": "黑暗香料殖民地",
    "Dark Spice Extractor": "黑暗香料萃取器",
    "Dark Spice Singularity": "黑暗香料奇点",
    "Dark Spice Strengthener": "黑暗香料加强器",
    "Dark Spice Laboratory": "黑暗香料实验室",
    "Offline Speed": "离线速度",
    "R: Distribute HALF Runes": "R：分发一半符文",
    "Name generation code by Airapport": "按机场命名生成代码",
    "Quality of life researches are no longer reset by Expansion": "生活质量研究不再被扩展重置",
    "Rainbow antispice is now uncapped, and a new antispice perk is unlocked": "彩虹反香料现在不封顶，并解锁一个新的反香料津贴",
    "SHARDS": "碎片",
    "Shift+R: Distribute ALL Runes": "Shift+R：分配所有符文",
    "Stop Ascending after Challenge 11:": "挑战11后停止转生：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Spice Idle v1.0.1": "香料放置 v1.0.1",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Your blue spice agencies are currently being boosted ": "您的 蓝色 香料代理当前提升了 ",
    "Your blue spice galaxies are currently being boosted ": "您的 蓝色 香料星系当前提升了 ",
    "Your blue spice harvesters are currently being boosted ": "您的 蓝色 香料收割机当前提升了 ",
    "Your blue spice machines are currently being boosted ": "您的 蓝色 香料机器当前提升了 ",
    "Your blue spice planets are currently being boosted ": "您的 蓝色 香料星球当前提升了 ",
    "Your blue spice factories are currently being boosted ": "您的 蓝色 香料工厂当前提升了 ",
    "Your red spice agencies are currently being boosted ": "您的 红色 香料代理当前提升了 ",
    "Your red spice galaxies are currently being boosted ": "您的 红色 香料星系当前提升了 ",
    "Your red spice harvesters are currently being boosted ": "您的 红色 香料收割机当前提升了 ",
    "Your red spice machines are currently being boosted ": "您的 红色 香料机器当前提升了 ",
    "Your red spice planets are currently being boosted ": "您的 红色 香料星球当前提升了 ",
    "Your red spice factories are currently being boosted ": "您的 红色 香料工厂当前提升了 ",
    "Your yellow spice agencies are currently being boosted ": "您的 黄色 香料代理当前提升了 ",
    "Your yellow spice galaxies are currently being boosted ": "您的 黄色 香料星系当前提升了 ",
    "Your yellow spice harvesters are currently being boosted ": "您的 黄色 香料收割机当前提升了 ",
    "Your yellow spice machines are currently being boosted ": "您的 黄色 香料机器当前提升了 ",
    "Your yellow spice planets are currently being boosted ": "您的 黄色 香料星球当前提升了 ",
    "Your yellow spice factories are currently being boosted ": "您的 黄色 香料工厂当前提升了 ",
    "Your green spice agencies are currently being boosted ": "您的 绿色 香料代理当前提升了 ",
    "Your green spice galaxies are currently being boosted ": "您的 绿色 香料星系当前提升了 ",
    "Your green spice harvesters are currently being boosted ": "您的 绿色 香料收割机当前提升了 ",
    "Your green spice machines are currently being boosted ": "您的 绿色 香料机器当前提升了 ",
    "Your green spice planets are currently being boosted ": "您的 绿色 香料星球当前提升了 ",
    "Your green spice factories are currently being boosted ": "您的 绿色 香料工厂当前提升了 ",
    "Your pink spice agencies are currently being boosted ": "您的 粉色 香料代理当前提升了 ",
    "Your pink spice galaxies are currently being boosted ": "您的 粉色 香料星系当前提升了 ",
    "Your pink spice harvesters are currently being boosted ": "您的 粉色 香料收割机当前提升了 ",
    "Your pink spice machines are currently being boosted ": "您的 粉色 香料机器当前提升了 ",
    "Your pink spice planets are currently being boosted ": "您的 粉色 香料星球当前提升了 ",
    "Your pink spice factories are currently being boosted ": "您的 粉色 香料工厂当前提升了 ",
    "(Currently: ": "(当前: ",
    "boosting ALL spice generators ": "提升所有香料生成器 ",
    "boosting all red spice generators ": "提升所有 红 色香料生成器 ",
    "boosting all blue spice generators ": "提升所有 蓝 色香料生成器 ",
    "boosting all pink spice generators ": "提升所有 粉 色香料生成器 ",
    "boosting all yellow spice generators ": "提升所有 黄 色香料生成器 ",
    "boosting all green spice generators ": "提升所有 绿 色香料生成器 ",
    "boosting all red & yellow spice generators ": "提升所有红色和黄色香料生成器 ",
    "Your crystallized spice furnaces are currently being boosted ": "您的结晶香料 熔炉 当前提升了 ",
    "Your crystallized spice headquarters are currently being boosted ": "您的结晶香料 总部 当前提升了 ",
    "Your crystallized spice industries are currently being boosted ": "您的结晶香料 工业 当前提升了 ",
    "Your crystallized spice intelligences are currently being boosted ": "您的结晶香料 智能 当前提升了 ",
    "Your crystallized spice refineries are currently being boosted ": "您的结晶香料 精炼厂 当前提升了 ",
    "Your crystallized spice singularities are currently being boosted ": "您的结晶香料 奇点 当前提升了 ",
    "Your green spice is boosting yellow spice production ": "你的绿色香料正在促进黄色香料的生产 ",
    "Your pink spice is boosting blue spice production ": "你的粉红色香料正在促进蓝色香料的生产 ",
    "Your red spice is boosting yellow, green, blue, & pink spice production ": "您的红色香料正在促进黄色、绿色、蓝色和粉色香料的生产 ",
    "Your yellow spice is boosting red spice production ": "你的黄色香料正在促进红色香料的生产 ",
    "Your crystallized spice is boosting pink spice production ": "您的结晶香料正在促进粉红色香料的生产 ",
    "and boosting red, yellow, green & blue spice production ": "并促进红色、黄色、绿色和蓝色香料的生产 ",
    "boosting all red, yellow & green spice generators ": "提升所有红色、黄色和绿色香料生成器 ",
    "boosting all red, yellow, green & blue spice generators ": "提升所有红色、黄色、绿色和蓝色的香料生成器 ",
    "Your blue spice is boosting green spice production ": "您的蓝色香料正在促进绿色香料的生产 ",
    "boosting all crystallized spice generators ": "提升所有结晶香料生成器 ",
    "boosting all normal spice generators ": "提升所有普通的香料生成器 ",
    "Average Ansuz rune gain: ": "平均 Ansuz 符文增益：",
    "Spice Idle v": "香料放置 v",
    "boosting arcane spice generators ": "增强奥术香料生成器 ",
    "Your arcane spice is boosting crystallized spice production ": "你的奥术香料正在促进结晶香料的生产",
    "Your arcane spice glyphs are currently being boosted ": "你的奥术香料 符号 当前被提升 ",
    "Your arcane spice shrines are currently being boosted ": "你的奥术香料 神社 当前被提升 ",
    "Your arcane spice spellbooks are currently being boosted ": "你的奥术香料 法术书 当前被提升 ",
    "Your arcane spice wizards are currently being boosted ": "你的奥术香料 巫师 当前被提升 ",
    "Your arcane spice cults are currently being boosted ": "你的奥术香料 崇拜 当前被提升 ",
    "Your arcane spice deities are currently being boosted ": "你的奥术香料 神祇 当前被提升 ",
    "boosting all arcane spice generators ": "提升所有奥术香料发生器 ",
    "Your crystallized spice empires are currently being boosted ": "您的结晶香料帝国目前提升了 ",
    "Arcane enchantments also boost arcane spice production ": "奥术附魔也提高了奥术香料的产量 ",
    "and boosting crystallized spice production ": "并提升结晶香料生产 ",
    "Your pink spice is boosting crystallized spice production ": "你的粉色香料正在提升结晶香料的生产 ",
    "Atomic spice efficiency: ": "原子香料效率：",
    "Data on this research: ": "这项研究的数据：",
    "Current unstable spice half-life: ": "目前不稳定香料半衰期：",
    "Estimated time to completion: ": "预计完成时间：",
    "Research #": "研究 #",
    "the resulting energy is boosting all normal spice production ": "由此产生的能量正在促进所有正常的香料生产 ",
    "Yellow spice production ": "黄色香料生产 ",
    "Green spice production ": "绿色香料生产 ",
    "Pink spice production ": "粉色香料生产 ",
    "Red spice production ": "红色香料生产 ",
    "Arcane spice production ": "奥术香料生产 ",
    "Blue spice production ": "蓝色香料生产 ",
    "Crystallized spice production ": "结晶香料生产 ",
    "improving synergy between colors by ": "改善颜色之间的协同作用 ",
    "Yellow, green, blue & pink spice production ": "黄色、绿色、蓝色和粉红色香料生产 ",
    "Your pure antispice is boosting arcane spice production ": "您的纯色反香料提升奥术香料的生产 ",
    "Your yellow antispice is boosting yellow spice production ": "您的黄色反香料提升黄色香料的生产 ",
    "Your red antispice is boosting red spice production ": "您的红色反香料提升红色香料的生产 ",
    "Your green antispice is boosting green spice production ": "您的绿色反香料提升绿色香料的生产 ",
    "Completions: ": "完成：",
    "Last updated ": "上次更新于 ",
    "and boosting arcane spice production ": "并提升奥术香料的生产",
    "Current boost: ": "当前提升：",
    "Rune power boosts are an extra 50% stronger (for up to ": "符文能量提升额外强 50%（最多 ",
    "Current atomic spice efficiency: ": "当前的原子香料效率：",
    "Current rune power production boost: ": "当前符文能量生产提升：",
    "Red, yellow, green & blue spice production ": "红色、黄色、绿色和蓝色香料生产 ",
    "and boosting all crystallized spice generators ": "并提升所有结晶香料生成器 ",
    "and boosting all arcane spice generators ": "并提升所有奥术香料生成器 ",
    "improving synergy between spices by ": "将香料之间的协同作用提高 ",
    "boosting crystallized spice production ": "将结晶香料产量提高 ",
    "Your basic antispice is boosting arcane spice production ": "你的基本反香料正在将奥术香料产量提高 ",
    "Your basic antispice is boosting arcane spice production ": "你的基本反香料正在促进奥术香料的生产 ",
    "Your blue antispice is boosting blue spice production ": "你的蓝色反香料将蓝色香料的产量提高了 ",
    "Your pink antispice is boosting pink spice production ": "你的粉红反香料使粉红香料的产量提高了 ",
    "Mode: ": "模式: ",
    "Time: ": "时间: ",
    "Your blue spice corporations are currently being boosted ": "您的蓝色香料公司目前增强了 ",
    "Your green spice corporations are currently being boosted ": "您的绿色香料公司目前增强了 ",
    "Your pink spice corporations are currently being boosted ": "您的粉色香料公司目前增强了 ",
    "Your red spice corporations are currently being boosted ": "您的红色香料公司目前增强了 ",
    "Your yellow spice corporations are currently being boosted ": "您的黄色香料公司目前增强了 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    " color boosts done": " 颜色提升完成",
    " ticks run": " ticks 运行",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\(([\d\.]+)x \-\> ([\d\.]+)x\)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)x\)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) kg$/,
    /^([\d\.]+) mg$/,
    /^([\d\.]+) μg$/,
    /^([\d\.]+) g$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\+([\d\.,]+) ᚫ$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^您(.+)$/,
    /^提升(.+)$/,
    /^每秒(.+)$/,
    /^你有(.+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) mg$/,
    /^([\d\.]+)e([\d\.]+)e([\d\.,]+)x$/,
    /^([\d\.]+)e([\d\.]+)e([\d\.,]+) mg$/,
    /^([\d\.]+)e([\d\.]+)e([\d\.,]+)x\)$/,
    /^([\d\.]+)e([\d\.]+)e([\d\.,]+)x,$/,
    /^([\d\.]+)e([\d\.]+)e([\d\.,]+) g$/,
    /^([\d\.]+)e([\d\.,]+) ᚫ$/,
    /^([\d\.]+)e([\d\.,]+)x\)$/,
    /^\+([\d\.]+)e([\d\.,]+) ᚫ$/,
    /^\-([\d\.]+)e([\d\.,]+) ᚫ$/,
    /^([\d\.]+)e([\d\.,]+)x,$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^([\d\.]+) minutes, ([\d\.]+) seconds$/, '$1 分，$2 秒'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^You have (.+) ᚫ.$/, '你有 $1 ᚫ.'],
    [/^Your unstable spice is decaying away with a half-life of (.+) milliseconds,$/, '你不稳定的香料正在以 $1 毫秒的半衰期衰减，'],
    [/^and has produced (.+) arcane spice deities$/, '并产生了 $1 奥术香料神'],
    [/^Next: Unstable spice decay will produce (.+) arcane spice deities$/, '下一个：不稳定的香料腐烂会产生 $1 奥术香料神'],
    [/^Currently: Unstable spice decay has produced (.+) arcane spice deities$/, '目前：不稳定的香料腐烂产生了 $1 个奥术香料神'],
    [/^Currently: Normal spice multipliers are (.+) stronger$/, '当前：普通香料倍增器强 $1'],
    [/^Next: Normal spice multipliers are (.+) stronger$/, '下一个: 普通香料倍增器强 $1'],
    [/^You have (.+) arcane enchantments \(\+(.+) free\),$/, '你有 $1 奥术附魔（\+$2 免费），'],
    [/^producing (.+) mg arcane spice\/sec,$/, '每秒产生 $1 毫克奥术香料，'],
    [/^producing (.+) blue spice corporations\/sec$/, '每秒产生 $1 蓝色香料公司，'],
    [/^producing (.+) green spice corporations\/sec$/, '每秒产生 $1 绿色香料公司，'],
    [/^producing (.+) red spice corporations\/sec$/, '每秒产生 $1 红色香料公司，'],
    [/^producing (.+) pink spice corporations\/sec$/, '每秒产生 $1 粉色香料公司，'],
    [/^producing (.+) yellow spice corporations\/sec$/, '每秒产生 $1 黄色香料公司，'],
    [/^and producing (.+) crystallized spice singularities\/sec$/, '并产生 $1 结晶香料奇点\/秒'],
    [/^The boost is currently (.+) stronger$/, '提升当前增强了 $1'],
    [/^Your unstable spice will be completely decayed in (.+) minutes$/, '你不稳定的香料将在 $1 分钟内完全腐烂'],
    [/^Your unstable spice is decaying away with a half-life of (.+) seconds,$/, '你不稳定的香料正在衰变，半衰期为 $1 秒，'],
    [/^When researching, you gain (.+) data\/sec$/, '研究时，你获得 $1 数据\/秒'],
    [/^Your unstable spice will be completely decayed in (.+) minutes, (.+) seconds$/, '你不稳定的香料将在 $1 分 $2 秒内完全腐烂'],
    [/^Your unstable spice will be completely decayed in (.+) seconds$/, '你不稳定的香料将在 $1 秒内完全腐烂'],
    [/^and making first generators (.+) stronger$/, '并使第 1 生成器强 $1'],
    [/^and making fourth generators (.+) stronger$/, '并使第 4 生成器强 $1'],
    [/^and making second generators (.+) stronger$/, '并使第 2 生成器强 $1'],
    [/^and making third generators (.+) stronger$/, '并使第 3 生成器强 $1'],
    [/^making crystal infusions and arcane enchantments (.+) stronger,$/, '使水晶灌注和奥术魔法强度提高 $1，'],
    [/^making color boosts and strengtheners (.+) stronger,$/, '使颜色提升和增强剂强度提高 1.00 倍，'],
    [/^Repeatable researches are (.+) stronger$/, '可重复性研究增强 $1'],
    [/^You have a total of (.+) rainbow antispice$/, '您总共有 $1 彩虹反香料'],
    [/^You have a total of (.+) Collapse challenge completions.$/, '您总共完成了 $1 次坍缩挑战。'],
    [/^Your basic antispice is boosting arcane spice production (.+),$/, '你的基本反香料正在将奥术香料产量提高 $1，'],
    [/^Your basic antispice is boosting arcane spice production (.+),$/, '你的基本反香料正在促进奥术香料的生产 $1，'],
    [/^Your blue antispice is boosting blue spice production (.+),$/, '你的蓝色反香料将蓝色香料的产量提高了 $1，'],
    [/^Your pink antispice is boosting pink spice production (.+),$/, '你的粉红反香料使粉红香料的产量提高了 $1，'],
    [/^ALL spice production multipliers are (.+) stronger$/, '所有香料产量乘数增强 $1'],
    [/^and making fifth generators (.+) stronger$/, '并使第五生成器增强 $1'],
    [/^and making sixth generators (.+) stronger$/, '并使第六台生成器变得增强 $1'],
    [/^When researching, you gain (.+) data\/sec, unaffected by game speed boosts$/, '研究时，您获得 $1 数据\/秒，不受游戏速度提升的影响'],
    [/^Repeatable researches are (.+) stronger$/, '可重复性研究强 $1'],
    [/^Reward: Normal spice multipliers are (.+) stronger$/, '奖励：普通香料倍数增强 $1'],
    [/^You have a total of (.+) rainbow antispice$/, '您总共有 $1 彩虹反香料'],
    [/^You have a total of (.+) Collapse challenge completions.$/, '您总共完成了 $1 次坍缩挑战。'],
    [/^Your unstable spice is decaying away with a half-life of (.+) microseconds,$/, '你不稳定的香料正在腐烂，半衰期为 $1 微秒，'],
    [/^ETA: (.+) seconds$/, 'ETA: $1 秒'],
    [/^ARCANE(.+)SPICE$/, '奥术香料'],
    [/^ASCENSION(.+)CHALLENGES$/, '转生挑战'],
    [/^PAST(.+)ASCENSIONS$/, '历史转生'],
    [/^PAST(.+)PRESTIGES$/, '历史声望'],
    [/^PRESTIGE(.+)UPGRADES$/, '声望升级'],
    [/^This research has been researched (.+) times$/, '此研究已被研究 $1 次'],
    [/^You have (.+) crystallized spice empires \((.+) bought\),$/, '你有 $1 结晶香料帝国（已购买 $2），'],
    [/^You have played for a total of ([\d\.]+) seconds.$/, '您总共玩了 $1 秒。'],
    [/^\#(.+) took (.+)s and gave (.+) ᚫ. (.+) ᚫ\/min$/, '\#$1 用了 $2 秒并给出了 $3 ᚫ。 $4 ᚫ\/分钟'],
    [/^You have produced a total of (.+) rune power.$/, '你总共产生了 $1 符文能力。'],
    [/^Average atomic spice gain: \+(.+) atomic\/min$/, '平均原子香料增益：\+$1 原子\/分钟'],
    [/^You have Collapsed (.+) times.$/, '你坍缩了 $1 次。'],
    [/^You have Ascended (.+) times.$/, '你转生了 $1 次。'],
    [/^You have accumulated a total of (.+) g spice in this Collapse.$/, '你在这次 坍缩 中总共积累了 $1 克 香料。'],
    [/^You have created a total of (.+) unstable spice.$/, '你总共创造了 $1 不稳定 香料。'],
    [/^You have (.+) arcane spice spellbooks \((.+) bought\),$/, '你有 $1 奥术香料 法术书（$2 已购买），'],
    [/^You have (.+) arcane spice deities \((.+) bought\),$/, '你有 $1 奥术香料 神祇（$2 已购买），'],
    [/^You have (.+) arcane spice cults \((.+) bought\),$/, '你有 $1 奥术香料 崇拜（$2 已购买），'],
    [/^You have (.+) arcane spice shrines \((.+) bought\),$/, '你有 $1 奥术香料 神社（$2 已购买），'],
    [/^You have (.+) arcane spice glyphs \((.+) bought\),$/, '你有 $1 奥术香料 符号（$2 已购买），'],
    [/^You have (.+) arcane spice wizards \((.+) bought\),$/, '你有 $1 奥术香料 巫师（$2 已购买），'],
    [/^You have (.+) ᚱ, producing (.+) ᚱ power\/sec$/, '你有 $1 ᚱ，产生 $2 ᚱ 能力\/秒'],
    [/^You have (.+) ᛟ, producing (.+) ᛟ power\/sec$/, '你有 $1 ᛟ，产生 $2 ᛟ 能力\/秒'],
    [/^You have (.+) ᛡ, producing (.+) ᛡ power\/sec$/, '你有 $1 ᛡ，产生 $2 ᛡ 能力\/秒'],
    [/^You have (.+) ᚱ power, boosting yellow, green, & blue spice production (.+)x$/, '您拥有 $1 ᚱ 能力，将黄色、绿色和蓝色香料产量提高 $2x'],
    [/^You have (.+) ᛟ power, boosting pink spice production (.+)x$/, '您拥有 $1 ᛟ 能力，将粉色香料产量提高 $2x'],
    [/^You have (.+) ᛡ power, boosting red spice production (.+)x$/, '您拥有 $1 ᛡ 能力，将红色色香料产量提高 $2x'],
    [/^You have (.+) pink spice corporations,$/, '你有 $1 粉色香料公司，'],
    [/^You have (.+) red spice corporations,$/, '你有 $1 红色香料公司，'],
    [/^You have (.+) yellow spice corporations,$/, '你有 $1 黄色香料公司，'],
    [/^You have (.+) green spice corporations,$/, '你有 $1 绿色香料公司，'],
    [/^You have (.+) blue spice corporations,$/, '你有 $1 蓝色香料公司，'],
    [/^You have (.+) color augments,$/, '你有 $1 颜色增强，'],
    [/^You have (.+) atomic spice.$/, '你有 $1 原子香料。'],
    [/^You have (.+) color boosts,$/, '你有 $1 颜色提升,'],
    [/^You have (.+) crystallized spice empires,$/, '你有 $1 结晶香料帝国，'],
    [/^You have (.+) arcane enchantments,$/, '你有 $1 奥术提升,'],
    [/^You have (.+) arcane spice strenghteners$/, '你有 $1 奥术香料增强剂,'],
    [/^You gain (.+) more Times Prestiged stat$/, '你获得 $1 的声望属性'],
    [/^Average rainbow spice gain: \+(.+) μg rainbow spice\/hour$/, '平均彩虹香料增益：\+$1 μg 彩虹香料\/小时'],
    [/^Average rainbow spice gain: \+(.+) μg rainbow spice\/min$/, '平均彩虹香料增益：\+$1 μg 彩虹香料\/分钟'],
    [/^You have Prestiged (.+) time.$/, '你声望了 $1 次。'],
    [/^You have Prestiged (.+) times.$/, '你声望了 $1 次。'],
    [/^\#(.+) took (.+) and gave (.+) atomic spice. \+(.+) atomic spice\/hour$/, '\#$1 花费 $2 并给予 $3 原子香料。 \+$4 原子香料\/小时'],
    [/^\#(.+) took (.+) and gave (.+) atomic spice. \+(.+) atomic spice\/min$/, '\#$1 花费 $2 并给予 $3 原子香料。 \+$4 原子香料\/分钟'],
    [/^\#(.+) took (.+) and gave (.+) μg rainbow spice. \+(.+) μg rainbow spice\/hour$/, '\#$1 花费 $2 并给予 $3 μg 彩虹香料。 \+$4 微克彩虹香料\/小时'],
    [/^\#(.+) took (.+) and gave (.+) μg rainbow spice. \+(.+) μg rainbow spice\/min$/, '\#$1 花费 $2 并给予 $3 μg 彩虹香料。 \+$4 微克彩虹香料\/分钟'],
    [/^You have done (.+) color shifts.$/, '您已经完成了 $1 次颜色偏移。'],
    [/^You have done (.+) color boosts.$/, '您已经完成了 $1 次颜色提升。'],
    [/^and (.+) g yellow spice.$/, '和 $1 克 黄色 香料。'],
    [/^and (.+) g pink spice.$/, '和 $1 克 粉色 香料。'],
    [/^and (.+) g blue spice.$/, '和 $1 克 蓝色 香料。'],
    [/^and (.+) g red spice.$/, '和 $1 克 红色 香料。'],
    [/^and (.+) g green spice.$/, '和 $1 克 绿色 香料。'],
    [/^Requires (.+) bought blue spice galaxies$/, '需要 $1 已购买 蓝色 香料星系'],
    [/^Requires (.+) bought pink spice galaxies$/, '需要 $1 已购买 粉色 香料星系'],
    [/^Requires (.+) bought red spice galaxies$/, '需要 $1 已购买 红色 香料星系'],
    [/^Requires (.+) bought green spice galaxies$/, '需要 $1 已购买 绿色 香料星系'],
    [/^Requires (.+) bought yellow spice galaxies$/, '需要 $1 已购买 黄色 香料星系'],
    [/^Requires (.+) blue spice galaxies$/, '需要 $1 蓝色 香料星系'],
    [/^Requires (.+) pink spice galaxies$/, '需要 $1 粉色 香料星系'],
    [/^Requires (.+) red spice galaxies$/, '需要 $1 红色 香料星系'],
    [/^Requires (.+) green spice galaxies$/, '需要 $1 绿色 香料星系'],
    [/^Requires (.+) yellow spice galaxies$/, '需要 $1 黄色 香料星系'],
    [/^You have (.+) crystallized spice strengtheners,$/, '你有 $1 结晶香料增强剂,'],
    [/^You have (.+) crystallized spice furnaces,$/, '你有 $1 结晶香料熔炉,'],
    [/^You have (.+) crystallized spice headquarters,$/, '你有 $1 结晶香料总部,'],
    [/^You have (.+) crystallized spice industries,$/, '你有 $1 结晶香料工业,'],
    [/^You have (.+) crystallized spice intelligences,$/, '你有 $1 结晶香料智能,'],
    [/^You have (.+) crystallized spice refineries,$/, '你有 $1 结晶香料精炼厂,'],
    [/^You have (.+) crystallized spice singularities,$/, '你有 $1 结晶香料奇点,'],
    [/^You have (.+) mg arcane spice.$/, '你有 $1 毫克 奥术 香料。'],
    [/^You have (.+) g arcane spice.$/, '你有 $1 克 奥术 香料。'],
    [/^You have (.+) g arcane spice$/, '你有 $1 克 奥术 香料'],
    [/^You have (.+) g red spice$/, '你有 $1 克 红色 香料'],
    [/^You have (.+) g blue spice$/, '你有 $1 克 蓝色 香料'],
    [/^You have (.+) g pink spice$/, '你有 $1 克 粉色 香料'],
    [/^You have (.+) g yellow spice$/, '你有 $1 克 黄色 香料'],
    [/^You have (.+) g green spice$/, '你有 $1 克 绿色 香料'],
    [/^You have (.+) g red spice.$/, '你有 $1 克 红色 香料.'],
    [/^You have (.+) g blue spice.$/, '你有 $1 克 蓝色 香料.'],
    [/^You have (.+) g pink spice.$/, '你有 $1 克 粉色 香料.'],
    [/^You have (.+) g yellow spice.$/, '你有 $1 克 黄色 香料.'],
    [/^You have (.+) g green spice.$/, '你有 $1 克 绿色 香料.'],
    [/^You have (.+) g crystallized spice.$/, '你有 $1 克 结晶 香料.'],
    [/^You have (.+) μg rainbow spice.$/, '你有 $1 微克 彩虹 香料.'],
    [/^You start with (.+) color shift$/, '您开始时有 $1 颜色偏移'],
    [/^You start with (.+) color shifts$/, '您开始时有 $1 颜色偏移'],
    [/^You get (.+) free crystal infusions$/, '您将获得 $1 次免费水晶灌注'],
    [/^You have played for a total of (.+) days, (.+) hours, (.+) minutes, (.+) seconds.$/, '您总共玩了 $1 天， $2 小时，$3 分钟，$4 秒。'],
    [/^You have played for a total of (.+) hour, (.+) minutes, (.+) seconds.$/, '您总共玩了 $1 小时， $2 分钟，$3 秒。'],
    [/^You have played for a total of (.+) hour, (.+) minute, (.+) seconds.$/, '您总共玩了 $1 小时， $2 分钟，$3 秒。'],
    [/^You have played for a total of (.+) hours, (.+) minute, (.+) seconds.$/, '您总共玩了 $1 小时， $2 分钟，$3 秒。'],
    [/^You have played for a total of (.+) hours, (.+) minutes, (.+) seconds.$/, '您总共玩了 $1 小时， $2 分钟，$3 秒。'],
    [/^You have played for a total of (.+) minutes, (.+) seconds.$/, '您总共玩了 $1 分，$2 秒.'],
    [/^You have played for a total of (.+) minutes.$/, '您总共玩了 $1 分.'],
    [/^You have played for a total of (.+) minutes$/, '您总共玩了 $1 分.'],
    [/^You have played for a total of (.+) seconds$/, '您总共玩了 $1 秒'],
    [/^You have spent (.+) minutes, (.+) seconds in this Prestige.$/, '您在此 声望 中花费了 $1 分 $2 秒。'],
    [/^You have spent (.+) hour, (.+) minutes, (.+) seconds in this Prestige.$/, '您在此 声望 中花费了 $1 小时, $2 分 ，$3 秒。'],
    [/^You have spent (.+) hour, (.+) minute, (.+) seconds in this Prestige.$/, '您在此 声望 中花费了 $1 小时, $2 分 ，$3 秒。'],
    [/^(.+) hours, (.+) minutes, (.+) seconds$/, '$1 小时, $2 分 ，$3 秒'],
    [/^You have spent (.+) hours, (.+) minutes, (.+) seconds in this Prestige.$/, '您在此 声望 中花费了 $1 小时, $2 分 ，$3 秒。'],
    [/^You have spent (.+) hours, (.+) minute, (.+) seconds in this Prestige.$/, '您在此 声望 中花费了 $1 小时, $2 分 ，$3 秒。'],
    [/^You have spent (.+) minutes this Prestige.$/, '您在此 声望 中花费了 $1 分。'],
    [/^You have spent (.+) seconds this Prestige.$/, '您在此 声望 中花费了 $1 秒。'],
    [/^You have spent (.+) minutes, (.+) seconds in this Collapse.$/, '您在此 坍缩 中花费了 $1 分钟，$2 秒。'],
    [/^You have spent (.+) seconds in this Prestige.$/, '您在此 声望 中花费了 $1 秒。'],
    [/^You have spent (.+) seconds in this Ascension.$/, '您在此 转生 中花费了 $1 秒。'],
    [/^You have accumulated a total of (.+) g spice$/, '您总共累积了 $1 克香料'],
    [/^You have accumulated a total of (.+) g spice.$/, '您总共累积了 $1 克香料.'],
    [/^and producing (.+) yellow spice galaxies\/sec$/, '并产生 $1 黄色香料 星系\/秒'],
    [/^and producing (.+) red spice galaxies\/sec$/, '并产生 $1 红色香料 星系\/秒'],
    [/^and producing (.+) blue spice galaxies\/sec$/, '并产生 $1 蓝色香料 星系\/秒'],
    [/^and producing (.+) green spice galaxies\/sec$/, '并产生 $1 绿色香料 星系\/秒'],
    [/^and producing (.+) pink spice galaxies\/sec$/, '并产生 $1 粉色香料 星系\/秒'],
    [/^You have (.+) arcane spice glyphs,$/, '你有 $1 奥术香料 符号，'],
    [/^You have (.+) arcane spice strenghteners,$/, '你有 $1 奥术香料 增强剂，'],
    [/^You have (.+) arcane spice strengtheners,$/, '你有 $1 奥术香料 增强剂，'],
    [/^You have (.+) arcane spice cults,$/, '你有 $1 奥术香料 崇拜，'],
    [/^You have (.+) arcane spice deities,$/, '你有 $1 奥术香料 神祇，'],
    [/^You have (.+) arcane spice spellbooks,$/, '你有 $1 奥术香料 法术书，'],
    [/^You have (.+) arcane spice wizards,$/, '你有 $1 奥术香料 巫师，'],
    [/^You have (.+) arcane spice shrines,$/, '你有 $1 奥术香料 神社，'],
    [/^You have (.+) color shifts,$/, '你有 $1 颜色偏移，'],
    [/^You have (.+) crystal infusions,$/, '你有 $1 水晶灌注，'],
    [/^You have (.+) crystallized spice strenghteners,$/, '你有 $1 结晶香料增强剂，'],
    [/^You have (.+) blue spice strengtheners,$/, '你有 $1 蓝色 香料增强剂，'],
    [/^You have (.+) green spice strengtheners,$/, '你有 $1 绿色 香料增强剂，'],
    [/^You have (.+) pink spice strengtheners,$/, '你有 $1 粉色 香料增强剂，'],
    [/^You have (.+) red spice strengtheners,$/, '你有 $1 红色 香料增强剂，'],
    [/^You have (.+) yellow spice strengtheners,$/, '你有 $1 黄色 香料增强剂，'],
    [/^You have (.+) blue spice agencies,$/, '你有 $1 蓝色 香料代理，'],
    [/^You have (.+) green spice agencies,$/, '你有 $1 绿色 香料代理，'],
    [/^You have (.+) pink spice agencies,$/, '你有 $1 粉色 香料代理，'],
    [/^You have (.+) red spice agencies,$/, '你有 $1 红色 香料代理，'],
    [/^You have (.+) yellow spice agencies,$/, '你有 $1 黄色 香料代理，'],
    [/^You have (.+) blue spice factories,$/, '你有 $1 蓝色 香料工厂，'],
    [/^You have (.+) green spice factories,$/, '你有 $1 绿色 香料工厂，'],
    [/^You have (.+) pink spice factories,$/, '你有 $1 粉色 香料工厂，'],
    [/^You have (.+) red spice factories,$/, '你有 $1 红色 香料工厂，'],
    [/^You have (.+) yellow spice factories,$/, '你有 $1 黄色 香料工厂，'],
    [/^You have (.+) blue spice galaxies,$/, '你有 $1 蓝色 香料星系，'],
    [/^You have (.+) green spice galaxies,$/, '你有 $1 绿色 香料星系，'],
    [/^You have (.+) pink spice galaxies,$/, '你有 $1 粉色 香料星系，'],
    [/^You have (.+) red spice galaxies,$/, '你有 $1 红色 香料星系，'],
    [/^You have (.+) yellow spice galaxies,$/, '你有 $1 黄色 香料星系，'],
    [/^You have (.+) blue spice machines,$/, '你有 $1 蓝色 香料机器，'],
    [/^You have (.+) green spice machines,$/, '你有 $1 绿色 香料机器，'],
    [/^You have (.+) pink spice machines,$/, '你有 $1 粉色 香料机器，'],
    [/^You have (.+) red spice machines,$/, '你有 $1 红色 香料机器，'],
    [/^You have (.+) yellow spice machines,$/, '你有 $1 黄色 香料机器，'],
    [/^You have (.+) blue spice planets,$/, '你有 $1 蓝色 香料星球，'],
    [/^You have (.+) green spice planets,$/, '你有 $1 绿色 香料星球，'],
    [/^You have (.+) pink spice planets,$/, '你有 $1 粉色 香料星球，'],
    [/^You have (.+) red spice planets,$/, '你有 $1 红色 香料星球，'],
    [/^You have (.+) yellow spice planets,$/, '你有 $1 黄色 香料星球，'],
    [/^You have (.+) blue spice harvesters,$/, '你有 $1 蓝色 香料收割机，'],
    [/^You have (.+) green spice harvesters,$/, '你有 $1 绿色 香料收割机，'],
    [/^You have (.+) pink spice harvesters,$/, '你有 $1 粉色 香料收割机，'],
    [/^You have (.+) red spice harvesters,$/, '你有 $1 红色 香料收割机，'],
    [/^You have (.+) yellow spice harvesters,$/, '你有 $1 黄色 香料收割机，'],
    [/^You have (.+) blue spice strenghteners,$/, '你有 $1 蓝色 香料增强剂，'],
    [/^You have (.+) green spice strenghteners,$/, '你有 $1 绿色 香料增强剂，'],
    [/^You have (.+) pink spice strenghteners,$/, '你有 $1 粉色 香料增强剂，'],
    [/^You have (.+) red spice strenghteners,$/, '你有 $1 红色 香料增强剂，'],
    [/^You have (.+) yellow spice strenghteners,$/, '你有 $1 黄色 香料增强剂，'],
    [/^You have (.+) blue spice planets \((.+) bought\),$/, '你有 $1 蓝色 香料星球 （$2 已购买），'],
    [/^You have (.+) green spice planets \((.+) bought\),$/, '你有 $1 绿色 香料星球 （$2 已购买），'],
    [/^You have (.+) pink spice planets \((.+) bought\),$/, '你有 $1 粉色 香料星球 （$2 已购买），'],
    [/^You have (.+) red spice planets \((.+) bought\),$/, '你有 $1 红色 香料星球 （$2 已购买），'],
    [/^You have (.+) yellow spice planets \((.+) bought\),$/, '你有 $1 黄色 香料星球 （$2 已购买），'],
    [/^You have (.+) blue spice galaxies \((.+) bought\),$/, '你有 $1 蓝色 香料星系 （$2 已购买），'],
    [/^You have (.+) green spice galaxies \((.+) bought\),$/, '你有 $1 绿色 香料星系 （$2 已购买），'],
    [/^You have (.+) pink spice galaxies \((.+) bought\),$/, '你有 $1 粉色 香料星系 （$2 已购买），'],
    [/^You have (.+) red spice galaxies \((.+) bought\),$/, '你有 $1 红色 香料星系 （$2 已购买），'],
    [/^You have (.+) yellow spice galaxies \((.+) bought\),$/, '你有 $1 黄色 香料星系 （$2 已购买），'],
    [/^You have (.+) blue spice harvesters \((.+) bought\),$/, '你有 $1 蓝色 香料收割机 （$2 已购买），'],
    [/^You have (.+) green spice harvesters \((.+) bought\),$/, '你有 $1 绿色 香料收割机 （$2 已购买），'],
    [/^You have (.+) pink spice harvesters \((.+) bought\),$/, '你有 $1 粉色 香料收割机 （$2 已购买），'],
    [/^You have (.+) red spice harvesters \((.+) bought\),$/, '你有 $1 红色 香料收割机 （$2 已购买），'],
    [/^You have (.+) yellow spice harvesters \((.+) bought\),$/, '你有 $1 黄色 香料收割机 （$2 已购买），'],
    [/^You have (.+) blue spice machines \((.+) bought\),$/, '你有 $1 蓝色 香料机器 （$2 已购买），'],
    [/^You have (.+) green spice machines \((.+) bought\),$/, '你有 $1 绿色 香料机器 （$2 已购买），'],
    [/^You have (.+) pink spice machines \((.+) bought\),$/, '你有 $1 粉色 香料机器 （$2 已购买），'],
    [/^You have (.+) red spice machines \((.+) bought\),$/, '你有 $1 红色 香料机器 （$2 已购买），'],
    [/^You have (.+) yellow spice machines \((.+) bought\),$/, '你有 $1 黄色 香料机器 （$2 已购买），'],
    [/^You have (.+) blue spice factories \((.+) bought\),$/, '你有 $1 蓝色 香料工厂 （$2 已购买），'],
    [/^You have (.+) green spice factories \((.+) bought\),$/, '你有 $1 绿色 香料工厂 （$2 已购买），'],
    [/^You have (.+) pink spice factories \((.+) bought\),$/, '你有 $1 粉色 香料工厂 （$2 已购买），'],
    [/^You have (.+) red spice factories \((.+) bought\),$/, '你有 $1 红色 香料工厂 （$2 已购买），'],
    [/^You have (.+) yellow spice factories \((.+) bought\),$/, '你有 $1 黄色 香料工厂 （$2 已购买），'],
    [/^You have (.+) blue spice agencies \((.+) bought\),$/, '你有 $1 蓝色 香料代理 （$2 已购买），'],
    [/^You have (.+) green spice agencies \((.+) bought\),$/, '你有 $1 绿色 香料代理 （$2 已购买），'],
    [/^You have (.+) pink spice agencies \((.+) bought\),$/, '你有 $1 粉色 香料代理 （$2 已购买），'],
    [/^You have (.+) red spice agencies \((.+) bought\),$/, '你有 $1 红色 香料代理 （$2 已购买），'],
    [/^You have (.+) yellow spice agencies \((.+) bought\),$/, '你有 $1 黄色 香料代理 （$2 已购买），'],
    [/^You have (.+) crystallized spice furnaces \((.+) bought\),$/, '你有 $1 结晶香料 熔炉 （$2 已购买），'],
    [/^You have (.+) crystallized spice refineries \((.+) bought\),$/, '你有 $1 结晶香料 精炼厂 （$2 已购买），'],
    [/^You have (.+) crystallized spice headquarters \((.+) bought\),$/, '你有 $1 结晶香料 总部 （$2 已购买），'],
    [/^You have (.+) crystallized spice intelligences \((.+) bought\),$/, '你有 $1 结晶香料 智能 （$2 已购买），'],
    [/^You have (.+) crystallized spice industries \((.+) bought\),$/, '你有 $1 结晶香料 工业 （$2 已购买），'],
    [/^You have (.+) crystal infusions \((.+) free\),$/, '你有 $1 水晶灌注 （$2 免费），'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Research(.+)Completed$/, '研究已完成'],
    [/^Pause(.+)Research$/, '暂停研究'],
    [/^You have spent (.+) minutes in this Collapse.$/, '您在此 坍缩 中花费了 $1 分钟。'],
    [/^You have (.+) crystallized spice singularities \((.+) bought\),$/, '你有 $1 结晶香料奇点（已购买 $2），'],
    [/^producing (.+) crystallized spice empires\/sec$/, '每秒产生 $1 结晶香料帝国'],
    [/^producing (.+) crystallized spice furnaces\/sec$/, '每秒产生 $1 结晶香料熔炉'],
    [/^producing (.+) crystallized spice headquarters\/sec$/, '每秒产生 $1 结晶香料总部'],
    [/^producing (.+) crystallized spice industries\/sec$/, '每秒产生 $1 结晶香料工业'],
    [/^producing (.+) crystallized spice intelligences\/sec$/, '每秒产生 $1 结晶香料智能'],
    [/^producing (.+) crystallized spice refineries\/sec$/, '每秒产生 $1 结晶香料精炼厂'],
    [/^producing (.+) crystallized spice singularities\/sec$/, '每秒产生 $1 结晶香料奇点'],
    [/^producing (.+) green spice agencies\/sec$/, '每秒产生 $1 个绿色 香料代理'],
    [/^producing (.+) blue spice agencies\/sec$/, '每秒产生 $1 个蓝色 香料代理'],
    [/^producing (.+) pink spice agencies\/sec$/, '每秒产生 $1 个粉色 香料代理'],
    [/^producing (.+) red spice agencies\/sec$/, '每秒产生 $1 个红色 香料代理'],
    [/^producing (.+) yellow spice agencies\/sec$/, '每秒产生 $1 个黄色 香料代理'],
    [/^producing (.+) green spice factories\/sec$/, '每秒产生 $1 个绿色 香料工厂'],
    [/^producing (.+) blue spice factories\/sec$/, '每秒产生 $1 个蓝色 香料工厂'],
    [/^producing (.+) pink spice factories\/sec$/, '每秒产生 $1 个粉色 香料工厂'],
    [/^producing (.+) red spice factories\/sec$/, '每秒产生 $1 个红色 香料工厂'],
    [/^producing (.+) yellow spice factories\/sec$/, '每秒产生 $1 个黄色 香料工厂'],
    [/^producing (.+) green spice harvesters\/sec$/, '每秒产生 $1 个绿色 香料收割机'],
    [/^producing (.+) blue spice harvesters\/sec$/, '每秒产生 $1 个蓝色 香料收割机'],
    [/^producing (.+) pink spice harvesters\/sec$/, '每秒产生 $1 个粉色 香料收割机'],
    [/^producing (.+) red spice harvesters\/sec$/, '每秒产生 $1 个红色 香料收割机'],
    [/^producing (.+) yellow spice harvesters\/sec$/, '每秒产生 $1 个黄色 香料收割机'],
    [/^producing (.+) green spice machines\/sec$/, '每秒产生 $1 个绿色 香料机器'],
    [/^producing (.+) blue spice machines\/sec$/, '每秒产生 $1 个蓝色 香料机器'],
    [/^producing (.+) pink spice machines\/sec$/, '每秒产生 $1 个粉色 香料机器'],
    [/^producing (.+) red spice machines\/sec$/, '每秒产生 $1 个红色 香料机器'],
    [/^producing (.+) yellow spice machines\/sec$/, '每秒产生 $1 个黄色 香料机器'],
    [/^producing (.+) green spice planets\/sec$/, '每秒产生 $1 个绿色 香料星球'],
    [/^producing (.+) blue spice planets\/sec$/, '每秒产生 $1 个蓝色 香料星球'],
    [/^producing (.+) pink spice planets\/sec$/, '每秒产生 $1 个粉色 香料星球'],
    [/^producing (.+) red spice planets\/sec$/, '每秒产生 $1 个红色 香料星球'],
    [/^producing (.+) yellow spice planets\/sec$/, '每秒产生 $1 个黄色 香料星球'],
    [/^producing (.+) green spice galaxies\/sec$/, '每秒产生 $1 个绿色 香料星系'],
    [/^producing (.+) blue spice galaxies\/sec$/, '每秒产生 $1 个蓝色 香料星系'],
    [/^producing (.+) pink spice galaxies\/sec$/, '每秒产生 $1 个粉色 香料星系'],
    [/^producing (.+) red spice galaxies\/sec$/, '每秒产生 $1 个红色 香料星系'],
    [/^producing (.+) arcane spice cults\/sec$/, '每秒产生 $1 奥术香料 崇拜'],
    [/^producing (.+) arcane spice shrines\/sec$/, '每秒产生 $1 奥术香料 神社'],
    [/^producing (.+) arcane spice wizards\/sec$/, '每秒产生 $1 奥术香料 巫师'],
    [/^producing (.+) arcane spice deities\/sec$/, '每秒产生 $1 奥术香料 神祇'],
    [/^producing (.+) arcane spice glyphs\/sec$/, '每秒产生 $1 奥术香料 符号'],
    [/^producing (.+) arcane spice spellbooks\/sec$/, '每秒产生 $1 奥术香料 法术书'],
    [/^producing (.+) yellow spice galaxies\/sec$/, '每秒产生 $1 个黄色 香料星系'],
    [/^producing (.+) g blue spice\/sec$/, '每秒产生 $1 克 蓝色 香料'],
    [/^producing (.+) g pink spice\/sec$/, '每秒产生 $1 克 粉色 香料'],
    [/^producing (.+) g red spice\/sec$/, '每秒产生 $1 克 红色 香料'],
    [/^producing (.+) g yellow spice\/sec$/, '每秒产生 $1 克 黄色 香料'],
    [/^producing (.+) g arcane spice\/sec$/, '每秒产生 $1 克 奥术 香料'],
    [/^producing (.+) g green spice\/sec$/, '每秒产生 $1 克 绿色 香料'],
    [/^producing (.+) g blue spice\/sec,$/, '每秒产生 $1 克 蓝色 香料，'],
    [/^producing (.+) g pink spice\/sec,$/, '每秒产生 $1 克 粉色 香料，'],
    [/^producing (.+) g red spice\/sec,$/, '每秒产生 $1 克 红色 香料，'],
    [/^producing (.+) g yellow spice\/sec,$/, '每秒产生 $1 克 黄色 香料，'],
    [/^producing (.+) g crystallized spice\/sec,$/, '每秒产生 $1 克 结晶 香料，'],
    [/^producing (.+) g green spice\/sec,$/, '每秒产生 $1 克 绿色 香料，'],
    [/^Currently running about (.+) ticks\/sec$/, '目前运行速度约为 3,000 ticks\/秒'],
    [/^\-(.+) atomic spice$/, '\-$1 原子 香料'],
    [/^\-(.+) g blue spice$/, '\-$1 克 蓝色 香料'],
    [/^\-(.+) g pink spice$/, '\-$1 克 粉色 香料'],
    [/^\-(.+) g red spice$/, '\-$1 克 红色 香料'],
    [/^\-(.+) g yellow spice$/, '\-$1 克 黄色 香料'],
    [/^\-(.+) g green spice$/, '\-$1 克 绿色 香料'],
    [/^\-(.+) g arcane spice$/, '\-$1 克 奥术 香料'],
    [/^\-(.+) mg arcane spice$/, '\-$1 毫克 奥术 香料'],
    [/^\+(.+) galactic shards$/, '\+$1 星系碎片'],
    [/^\+(.+) atomic spice$/, '\+$1 原子 香料'],
    [/^\+(.+) unstable spice$/, '\+$1 不稳定 香料'],
    [/^\+(.+) μg rainbow spice\/sec$/, '\+$1 微克 彩虹香料\/秒'],
    [/^\+(.+) g arcane spice\/sec$/, '\+$1 克 奥术香料\/秒'],
    [/^\+(.+) mg arcane spice\/sec$/, '\+$1 毫克 奥术香料\/秒'],
    [/^(.+) μg rainbow spice$/, '$1 微克 彩虹 香料'],
    [/^(.+) g crystallized spice$/, '$1 克 结晶 香料'],
    [/^(.+) g blue spice\/sec$/, '每秒 $1 克 蓝色 香料'],
    [/^(.+) g pink spice\/sec$/, '每秒 $1 克 粉色 香料'],
    [/^(.+) g red spice\/sec$/, '每秒 $1 克 红色 香料'],
    [/^(.+) g yellow spice\/sec$/, '每秒 $1 克 黄色 香料'],
    [/^(.+) g green spice\/sec$/, '每秒 $1 克 绿色 香料'],
    [/^(.+) g crystallized spice\/sec$/, '每秒 $1 克 结晶 香料'],
    [/^(.+) g blue spice,$/, '$1 克 蓝色 香料，'],
    [/^(.+) g green spice,$/, '$1 克 绿色 香料，'],
    [/^(.+) g yellow spice,$/, '$1 克 黄色 香料，'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^\+([\d\.]+)e([\d\.,]+) ᚫ\/min$/, '\+$1e$2 ᚫ\/分钟'],
    [/^([\d\.]+)e([\d\.,]+) μg$/, '$1e$2 微克'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) g$/, '$1 克'],
    [/^([\d\.]+) days, ([\d\.]+) hours, ([\d\.]+) minutes, ([\d\.]+) seconds$/, '$1 天，$2 小时，$3 分钟，$4 秒'],
    [/^([\d\.]+) minutes$/, '$1 分钟'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+) industries$/, '$1 工业'],
    [/^([\d\.]+) glyphs$/, '$1 符号'],
    [/^([\d\.]+) furnaces$/, '$1 熔炉'],
    [/^([\d\.]+) harvesters$/, '$1 收割机'],
    [/^([\d\.]+) refineries$/, '$1 精炼厂'],
    [/^([\d\.]+) singularities$/, '$1 奇点'],
    [/^([\d\.]+) empires$/, '$1 帝国'],
    [/^([\d\.]+) agencies$/, '$1 代理'],
    [/^([\d\.]+) cults$/, '$1 崇拜'],
    [/^([\d\.]+) MS$/, '$1 毫秒'],
    [/^([\d\.]+) seconds$/, '$1 秒'],
    [/^([\d\.]+) deities$/, '$1 神灵'],
    [/^([\d\.]+) factories$/, '$1 工厂'],
    [/^([\d\.]+) milliseconds$/, '$1 毫秒'],
    [/^([\d\.]+) galaxies$/, '$1 星系'],
    [/^([\d\.]+) headquarters$/, '$1 总部'],
    [/^([\d\.]+) spellbooks$/, '$1 魔法书'],
    [/^([\d\.]+) wizards$/, '$1 巫师'],
    [/^([\d\.]+) shrines$/, '$1 神殿'],
    [/^([\d\.]+) planets$/, '$1 行星'],
    [/^([\d\.]+) machines$/, '$1 机器'],
    [/^Challenge ([\d\.]+) completed$/, '挑战 $1 已完成'],
    [/^Challenge ([\d\.]+)$/, '挑战 $1'],
    [/^Unlocks Challenge ([\d\.]+)$/, '解锁挑战 $1'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) g$/, '$1e$2 克'],
    [/^([\d\.]+)e([\d\.,]+) atomic spice$/, '$1e$2 原子香料'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.]+)e([\d\.,]+) g green spice,$/, '$1e$2 g 绿色 香料,'],
    [/^([\d\.]+)e([\d\.,]+) g yellow spice$/, '$1e$2 g 黄色 香料'],
    [/^([\d\.]+)e([\d\.,]+) g yellow spice,$/, '$1e$2 g 黄色 香料,'],
    [/^([\d\.]+)e([\d\.,]+) g blue spice,$/, '$1e$2 g 蓝色 香料,'],
    [/^([\d\.]+)e([\d\.,]+) g pink spice,$/, '$1e$2 g 粉色 香料,'],
    [/^([\d\.]+)e([\d\.,]+) g red spice$/, '$1e$2 g 红色 香料'],
    [/^([\d\.]+)e([\d\.,]+) g red spice,$/, '$1e$2 g 红色 香料,'],
    [/^([\d\.]+)e([\d\.,]+) μg rainbow spice for next (.+)$/, '$1e$2 μg 彩虹香料为下一个 $3'],
    [/^([\d\.]+)e([\d\.]+)e([\d\.,]+) g red spice$/, '$1e$2e$3 g 红色 香料'],
    [/^([\d\.]+)e([\d\.]+)e([\d\.,]+) g red spice,$/, '$1e$2e$3 g 红色 香料,'],
    [/^([\d\.]+)e([\d\.,]+) μg rainbow spice required$/, '需要 $1e$2 μg 彩虹 香料'],
    [/^([\d\.,]+) g$/, '$1 克'],
    [/^([\d\.,]+) microseconds$/, '$1 微秒'],
    [/^([\d\.,]+) units$/, '$1 单位'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^Buy until ([\d\.,]+):$/, '购买单位 $1：'],
    [/^\#([\d\.,]+) \(no data\)$/, '\#$1（无数据）'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^\+(.+) yellow antispice$/, '\+$1 黄色反香料'],
    [/^\+(.+) red antispice$/, '\+$1 红色反香料'],
    [/^\+(.+) basic antispice$/, '\+$1 基础反香料'],
    [/^Currently: (.+) free arcane enchantments$/, '当前：$1 免费的奥术附魔'],
    [/^Currently: (.+) atomic spice\/min\n(.+)Peak: (.+) atomic spice\/min at (.+) atomic spice$/, '当前：$1 原子香料\/分钟\n$2峰值：$3 原子香料\/分钟，$4 原子香料'],
    [/^Currently: (.+) μg rainbow spice\/min\n(.+)Peak: (.+) μg rainbow spice\/min at (.+) color boosts$/, '当前：$1 μg 彩虹香料\/分钟\n$2峰值：$3 μg 彩虹香料\/分钟 $4 颜色增强'],
    [/^Currently: (.+) ᚫ\/min\n(.+)Peak: (.+) ᚫ\/min at (.+) ᚫ$/, '当前：$1 ᚫ\/分钟\n$2峰值：$3 ᚫ/分钟 $4 ᚫ'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^(.+) ticks run \(capped\)$/, '$1 tick运行（上限）'],
    [/^(.+) color augments done$/, '$1 颜色增强完成'],
    [/^You have done (.+) color augments.$/, '你完成了 $1 颜色增强.'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);